Repository aquaproj/aqua-registry, pull requests merged in 2021-12, with the labels that each got.

#810 feat: add `kvaps/kubectl-node-shell`
  .gitignore
  aqua-all.yaml
  registry.yaml
Labels: enhancement

#813 feat: support M1 Mac
  registry.yaml
Labels: enhancement

#831 fix: support `fishworks/gofish` in M1 Mac
  registry.yaml
Labels: bug

#834 fix: support telepresence M1 Mac
  registry.yaml
Labels: bug

#843 feat: add `jesseduffield/horcrux`
  aqua-all.yaml
  registry.yaml
Labels: enhancement

#845 feat: add `google/go-containerregistry`
  aqua-all.yaml
  registry.yaml
Labels: enhancement

#852 add sharkdp/bat
  aqua-all.yaml
  registry.yaml
Labels: enhancement

#854 Add `bootandy/dust` and more
  aqua-all.yaml
  registry.yaml
Labels: enhancement

#855 feat: add `nodejs/node`
  aqua-all.yaml
  registry.yaml
Labels: enhancement

#860 feat: add `marcosnils/bin`
  aqua-all.yaml
  registry.yaml
Labels: enhancement

#862 docs: update CONTRIBUTING
  CONTRIBUTING.md
Labels: documentation

#864 feat: add `argoproj-labs/argocd-autopilot`
  aqua-all.yaml
  registry.yaml
Labels: enhancement

#865 feat: add `loft-sh/devspace`
  aqua-all.yaml
  registry.yaml
Labels: enhancement

#869 feat: add `neovim/neovim`
  aqua-all.yaml
  registry.yaml
Labels: enhancement

#866 feat: add `inlets/inlets-pro`
  aqua-all.yaml
  registry.yaml
Labels: enhancement

#871 feat: add `kastenhq/external-tools/k10multicluster`
  aqua-all.yaml
  registry.yaml
Labels: enhancement

#873 feat: add `kanisterio/kanister`
  aqua-all.yaml
  registry.yaml
Labels: enhancement

#893 feat: add `kastenhq/kubestr`
  .github/workflows/test.yaml
  aqua-all.yaml
  registry.yaml
Labels: enhancement

#894 feat: add `johanhaleby/kubetail`
  aqua-all.yaml
  registry.yaml
Labels: enhancement

#895 feat: add `FairwindsOps/polaris`
  aqua-all.yaml
  registry.yaml
Labels: enhancement

#1046 feat: add `derailed/popeye`
  aqua-all.yaml
  registry.yaml
Labels: enhancement

#1190 feat: add `porter-dev/porter`
  aqua-all.yaml
  registry.yaml
Labels: enhancement

#1224 feat: `sigstore/rekor`
  aqua-all.yaml
  registry.yaml
Labels: enhancement

#1225 feat: add `tilt-dev/tilt`
  aqua-all.yaml
  registry.yaml
Labels: enhancement

#1226 feat: add `tektoncd/cli`
  aqua-all.yaml
  registry.yaml
Labels: enhancement

#1233 feat: add `containerd/nerdctl`
  .github/workflows/test.yaml
  registry.yaml
  tests/c.yaml
Labels: enhancement

#1235 feat: add `alexellis/k3sup`
  registry.yaml
  tests/a.yaml
Labels: enhancement

#1237 fix: rename the directory `tests` to `pkgs`
  .github/workflows/test.yaml
  CONTRIBUTING.md
  aqua-all.yaml
  pkgs/.gitkeep
  pkgs/a.yaml
  pkgs/b.yaml
  pkgs/c.yaml
  pkgs/d.yaml
  pkgs/e.yaml
  pkgs/f.yaml
  pkgs/g.yaml
  pkgs/h.yaml
  pkgs/i.yaml
  pkgs/j.yaml
  pkgs/k.yaml
  pkgs/l.yaml
  pkgs/m.yaml
  pkgs/n.yaml
  pkgs/o.yaml
  pkgs/p.yaml
  pkgs/q.yaml
  pkgs/r.yaml
  pkgs/s.yaml
  pkgs/t.yaml
  pkgs/u.yaml
  pkgs/v.yaml
  pkgs/w.yaml
  pkgs/x.yaml
  pkgs/y.yaml
  pkgs/z.yaml
  renovate.json5
Labels: bug

#1248 feat: use supported_if
  registry.yaml
Labels: enhancement

#1250 feat: add `jreleaser/jreleaser` and `jreleaser/jreleaser/standalone`
  pkgs/j.yaml
  registry.yaml
Labels: enhancement

#1251 fix: fix the format
  pkgs/j.yaml
Labels: bug

#1256 feat: add `sachaos/viddy`
  pkgs/s.yaml
  registry.yaml
Labels: enhancement

#1258 feat: add `hashicorp/terraform-ls`
  pkgs/h.yaml
  registry.yaml
Labels: enhancement

#1259 feat: add `thazelart/terraform-validator`
  pkgs/t.yaml
  registry.yaml
Labels: enhancement

#1260 feat: add `juliosueiras/terraform-lsp`
  pkgs/j.yaml
  registry.yaml
Labels: enhancement

#1263 fix: fix jreleaser/jreleaser/standalone for M1 Mac
  registry.yaml
Labels: bug

#1267 feat: add `vmware-tanzu/carvel-vendir`
  pkgs/v.yaml
  registry.yaml
Labels: enhancement

#1268 feat: use the field `rosetta2`
  registry.yaml
Labels: breaking change

#1271 feat: add `sclevine/yj`
  pkgs/s.yaml
  registry.yaml
Labels: enhancement

#1272 feat: add `wtfutil/wtf`
  pkgs/w.yaml
  registry.yaml
Labels: enhancement

#1277 feat: add `variantdev/vals`
  pkgs/v.yaml
  registry.yaml
Labels: enhancement

#1278 feat: add `xo/usql`
  pkgs/x.yaml
  registry.yaml
Labels: enhancement

#1281 feat: add `vmware-tanzu/velero`
  pkgs/v.yaml
  registry.yaml
Labels: enhancement

#1282 feat: add `loft-sh/vcluster`
  pkgs/l.yaml
  registry.yaml
Labels: enhancement

#1292 feat: add `noborus/trdsql`
  pkgs/n.yaml
  registry.yaml
Labels: enhancement

#1293 feat: add `grafana/tanka`
  pkgs/g.yaml
  registry.yaml
Labels: enhancement

#1294 feat: add `talos-systems/talos`
  pkgs/t.yaml
  registry.yaml
Labels: enhancement

#1295 feat: add `anchore/syft`
  pkgs/a.yaml
  registry.yaml
Labels: enhancement

#1296 feat: add `aquasecurity/starboard`
  pkgs/a.yaml
  registry.yaml
Labels: enhancement

#1297 feat: add `geofffranks/spruce`
  pkgs/g.yaml
  registry.yaml
Labels: enhancement

#1299 feat: add `spinnaker/spin`
  pkgs/s.yaml
  registry.yaml
Labels: enhancement

#1300 feat: add `mozilla/sops`
  pkgs/m.yaml
  registry.yaml
Labels: enhancement

#1307 feat: add `slok/sloth`
  pkgs/s.yaml
  registry.yaml
Labels: enhancement

#1308 feat: add `plexsystems/sinker`
  pkgs/p.yaml
  registry.yaml
Labels: enhancement

#1309 feat: add `scaleway/scaleway-cli`
  pkgs/s.yaml
  registry.yaml
Labels: enhancement

#1310 feat: add `Versent/saml2aws`
  pkgs/v.yaml
  registry.yaml
Labels: enhancement

#1311 feat: add `rancher/rke`
  pkgs/r.yaml
  registry.yaml
Labels: enhancement

#1312 feat: add `kyoh86/richgo`
  pkgs/k.yaml
  registry.yaml
Labels: enhancement

#1313 feat: add `genuinetools/reg`
  pkgs/g.yaml
  registry.yaml
Labels: enhancement

#1314 feat: add `FairwindsOps/rbac-lookup`
  pkgs/f.yaml
  registry.yaml
Labels: enhancement

#1315 feat: add `FairwindsOps/pluto`
  pkgs/f.yaml
  registry.yaml
Labels: enhancement

#1316 feat: add `pivotal-cf/om`
  pkgs/p.yaml
  registry.yaml
Labels: enhancement

#1317 feat: add `pivotal-cf/pivnet-cli`
  pkgs/p.yaml
  registry.yaml
Labels: enhancement

#1318 feat: add `okteto/okteto`
  pkgs/o.yaml
  registry.yaml
Labels: enhancement

#1319 feat: add `vektra/mockery`
  pkgs/v.yaml
  registry.yaml
Labels: enhancement

#1320 feat: add `minishift/minishift`
  pkgs/m.yaml
  registry.yaml
Labels: enhancement

#1321 feat: add `magefile/mage`
  pkgs/m.yaml
  registry.yaml
Labels: enhancement

#1324 feat: add `benbjohnson/litestream`
  pkgs/b.yaml
  registry.yaml
Labels: enhancement

#1325 feat: add `hashicorp/levant`
  pkgs/h.yaml
  registry.yaml
Labels: enhancement

#1326 feat: add `zaquestion/lab`
  pkgs/z.yaml
  registry.yaml
Labels: enhancement

#1327 feat: add `vmware-tanzu/carvel-kwt`
  pkgs/v.yaml
  registry.yaml
Labels: enhancement

#1328 feat: add `kudobuilder/kuttl`
  pkgs/k.yaml
  registry.yaml
Labels: enhancement

#1329 feat: add `pulumi/kubespy`
  pkgs/p.yaml
  registry.yaml
Labels: enhancement

#1330 feat: add `controlplaneio/kubesec`
  pkgs/c.yaml
  registry.yaml
Labels: enhancement

#1331 feat: add `gruntwork-io/kubergrunt`
  pkgs/g.yaml
  registry.yaml
Labels: enhancement

#1332 feat: add `kubemq-io/kubemqctl`
  pkgs/g.yaml
  pkgs/j.yaml
  pkgs/k.yaml
  pkgs/l.yaml
  pkgs/p.yaml
  pkgs/v.yaml
  registry.yaml
Labels: enhancement

#1333 feat: add `helm/chart-releaser`
  pkgs/a.yaml
  pkgs/f.yaml
  pkgs/g.yaml
  pkgs/h.yaml
  pkgs/i.yaml
  registry.yaml
Labels: enhancement

#1335 feat: add `vmware-tanzu/carvel-imgpkg`
  pkgs/e.yaml
  pkgs/g.yaml
  pkgs/m.yaml
  pkgs/n.yaml
  pkgs/p.yaml
  pkgs/s.yaml
  pkgs/v.yaml
  registry.yaml
Labels: enhancement

#1339 feat: add `Kong/deck`
  pkgs/a.yaml
  pkgs/b.yaml
  pkgs/c.yaml
  pkgs/g.yaml
  pkgs/k.yaml
  pkgs/s.yaml
  pkgs/t.yaml
  registry.yaml
Labels: enhancement

#1340 feat: add `cloudflare/cloudflared`
  pkgs/b.yaml
  pkgs/c.yaml
  pkgs/s.yaml
  registry.yaml
Labels: enhancement

#1342 feat: add `Traackr/binnacle`
  pkgs/9.yaml
  pkgs/a.yaml
  pkgs/r.yaml
  pkgs/t.yaml
  registry.yaml
Labels: enhancement

#1350 feat: add `batchcorp/plumber`
  pkgs/b.yaml
  registry.yaml
Labels: enhancement

#1351 feat: add `ajeetdsouza/zoxide`
  pkgs/a.yaml
  pkgs/c.yaml
  pkgs/d.yaml
  pkgs/g.yaml
  pkgs/h.yaml
  pkgs/r.yaml
  pkgs/s.yaml
  pkgs/v.yaml
  pkgs/w.yaml
  registry.yaml
Labels: enhancement

#1354 fix: enable rostta2 for kustomize
  pkgs/k.yaml
  registry.yaml
Labels: bug

#1355 feat: add `extrawurst/gitui`
  pkgs/d.yaml
  pkgs/e.yaml
  pkgs/s.yaml
  registry.yaml
Labels: enhancement

#1358 feat: add `shellspec/shellspec`
  pkgs/b.yaml
  pkgs/e.yaml
  pkgs/f.yaml
  pkgs/g.yaml
  pkgs/j.yaml
  pkgs/k.yaml
  pkgs/n.yaml
  pkgs/s.yaml
  registry.yaml
Labels: enhancement

#1382 feat: add `Schniz/fnm`, etc
  pkgs/a.yaml
  pkgs/d.yaml
  pkgs/s.yaml
  pkgs/w.yaml
  registry.yaml
Labels: enhancement

#1385 fix: enable rosetta2
  registry.yaml
Labels: bug

#1412 docs: update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#1437 fix: remove Node.js
  pkgs/n.yaml
  registry.yaml
Labels: breaking change, remove

#1386 feat: use `semverWithVersion`
  registry.yaml
Labels: breaking change

#1463 feat: add `suzuki-shunsuke/asciinema-trim`
  pkgs/s.yaml
  registry.yaml
Labels: enhancement

#1525 feat: add `up9inc/mizu`
  pkgs/u.yaml
  registry.yaml
Labels: enhancement

#1526 feat: add `zellij-org/zellij`
  pkgs/z.yaml
  registry.yaml
Labels: enhancement

#1540 feat: add `mercari/tfnotify`
  pkgs/m.yaml
  registry.yaml
Labels: enhancement

#1541 feat: add `wader/fq`
  pkgs/w.yaml
  registry.yaml
Labels: enhancement

#1549 bob repo added to registry
  pkgs/b.yaml
  registry.yaml
Labels: enhancement

#1551 feat: add `rhysd/actionlint`
  pkgs/r.yaml
  registry.yaml
Labels: enhancement

#1575 feat: add `goreleaser/nfpm`
  pkgs/g.yaml
  registry.yaml
Labels: enhancement

#1576 feat: add `operator-framework/operator-sdk`
  pkgs/o.yaml
  registry.yaml
Labels: enhancement

#1594 feat: add `grafana/loki/logcli`
  pkgs/g.yaml
  registry.yaml
Labels: enhancement

#1595 feat: add `jetstack/cert-manager/cmctl`
  pkgs/j.yaml
  registry.yaml
Labels: enhancement

#1605 docs: update `aqua g`
  README.md
Labels: documentation

#1606 feat: add `liamg/memit`
  pkgs/l.yaml
  pkgs/u.yaml
  pkgs/x.yaml
  registry.yaml
Labels: enhancement

#1607 feat: add `Jeffail/benthos`
  pkgs/j.yaml
  registry.yaml
Labels: enhancement

#1612 feat: add `infracost/infracost`
  pkgs/i.yaml
  registry.yaml
Labels: enhancement
