Repository aquaproj/aqua-registry, pull requests merged in 2022-05, with the labels that each got.

#3239 feat: add registry.json
  .prettierignore
  CONTRIBUTING.md
  aqua-ci.yaml
  aqua-dev.yaml
  generate-registry.sh
  registry.json
Labels: enhancement

#3249 feat: add knqyf263/cob
  pkgs/knqyf263/cob/pkg.yaml
  pkgs/knqyf263/cob/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3250 feat: add mergestat/mergestat
  pkgs/mergestat/mergestat/pkg.yaml
  pkgs/mergestat/mergestat/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3251 feat: add projectdiscovery/naabu and projectdiscovery/httpx
  pkgs/projectdiscovery/httpx/pkg.yaml
  pkgs/projectdiscovery/httpx/registry.yaml
  pkgs/projectdiscovery/naabu/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3270 Revert "chore(deps): update dependency antonmedv/fx to v20.0.2"
  pkgs/antonmedv/fx/pkg.yaml
Labels: bug

#3272 fix: pin tool versions
  pkgs/anchore/syft/pkg.yaml
  pkgs/argoproj-labs/argocd-image-updater/pkg.yaml
  pkgs/b4b4r07/gist/pkg.yaml
  pkgs/blacknon/hwatch/pkg.yaml
Labels: bug

#3262 test: test multiple version
  pkgs/emirozer/kubectl-doctor/pkg.yaml
  pkgs/golang-migrate/migrate/pkg.yaml
  pkgs/golang-migrate/migrate/registry.yaml
  registry.yaml
Labels: bug

#3274 test: test multiple versions
  pkgs/harelba/q/pkg.yaml
  pkgs/harelba/q/registry.yaml
  pkgs/iawia002/lux/pkg.yaml
  pkgs/kubernetes-sigs/krew/pkg.yaml
  pkgs/zricethezav/gitleaks/pkg.yaml
  pkgs/zricethezav/gitleaks/registry.yaml
  registry.yaml
Labels: bug

#3289 docs: test multiple versions
  CONTRIBUTING.md
Labels: documentation

#3288 test: test multiple versions (replicatedhq/kots)
  pkgs/replicatedhq/kots/pkg.yaml
  pkgs/replicatedhq/kots/registry.yaml
  registry.yaml
Labels: bug

#3294 fix: fix GoogleCloudPlatform/terraformer/aws
  pkgs/GoogleCloudPlatform/terraformer/aws/registry.yaml
  registry.yaml
Labels: bug

#3297 fix: remove fishworks/gofish
  pkgs/fishworks/gofish/pkg.yaml
  pkgs/fishworks/gofish/registry.yaml
  registry.yaml
Labels: bug

#3324 feat: add suzuki-shunsuke/yaml2json
  pkgs/suzuki-shunsuke/yaml2json/pkg.yaml
  pkgs/suzuki-shunsuke/yaml2json/registry.yaml
  registry.yaml
Labels: enhancement

#3329 docs: arrange badges
  README.md
Labels: documentation

#3332 feat: add ropnop/kerbrute
  pkgs/ropnop/kerbrute/pkg.yaml
  pkgs/ropnop/kerbrute/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3371 feat: add BeryJu/korb
  pkgs/BeryJu/korb/pkg.yaml
  pkgs/BeryJu/korb/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3372 feat: add chanzuckerberg/fogg
  pkgs/chanzuckerberg/fogg/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3400 feat: add peak/s5cmd
  pkgs/peak/s5cmd/pkg.yaml
  pkgs/peak/s5cmd/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3401 feat: add TimothyYe/skm
  pkgs/TimothyYe/skm/pkg.yaml
  pkgs/TimothyYe/skm/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3402 feat: add mantil-io/mantil
  pkgs/mantil-io/mantil/pkg.yaml
  pkgs/mantil-io/mantil/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3403 feat: add xitonix/trubka
  pkgs/xitonix/trubka/pkg.yaml
  pkgs/xitonix/trubka/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3405 feat: add sanathp/statusok
  pkgs/sanathp/statusok/pkg.yaml
  pkgs/sanathp/statusok/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3406 feat: add rlmcpherson/s3gof3r
  pkgs/rlmcpherson/s3gof3r/pkg.yaml
  pkgs/rlmcpherson/s3gof3r/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3407 feat: add bengadbois/pewpew
  pkgs/bengadbois/pewpew/pkg.yaml
  pkgs/bengadbois/pewpew/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3408 feat: add xwjdsh/manssh
  pkgs/xwjdsh/manssh/pkg.yaml
  pkgs/xwjdsh/manssh/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3411 feat: add timdp/lwc
  pkgs/timdp/lwc/pkg.yaml
  pkgs/timdp/lwc/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3412 fix(timdp/lwc): ignore darwin
  pkgs/timdp/lwc/registry.yaml
  registry.json
  registry.yaml
Labels: bug

#3419 feat: add ivanilves/lstags
  pkgs/ivanilves/lstags/pkg.yaml
  pkgs/ivanilves/lstags/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3423 feat: add kool-dev/kool
  pkgs/kool-dev/kool/pkg.yaml
  pkgs/kool-dev/kool/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3424 feat: add cswank/kcli
  pkgs/cswank/kcli/pkg.yaml
  pkgs/cswank/kcli/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3426 feat: add jenkins-zh/jenkins-cli
  pkgs/jenkins-zh/jenkins-cli/pkg.yaml
  pkgs/jenkins-zh/jenkins-cli/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3427 feat: add gocruncher/jenkins-job-cli
  pkgs/gocruncher/jenkins-job-cli/pkg.yaml
  pkgs/gocruncher/jenkins-job-cli/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3428 feat: add dnnrly/abbreviate
  pkgs/dnnrly/abbreviate/pkg.yaml
  pkgs/dnnrly/abbreviate/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3429 feat: add becheran/roumon
  pkgs/becheran/roumon/pkg.yaml
  pkgs/becheran/roumon/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3430 feat: add gabrie30/ghorg
  pkgs/gabrie30/ghorg/pkg.yaml
  pkgs/gabrie30/ghorg/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3431 feat: add mkchoi212/fac
  pkgs/mkchoi212/fac/pkg.yaml
  pkgs/mkchoi212/fac/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3434 feat: add ozankasikci/dockerfile-generator
  pkgs/ozankasikci/dockerfile-generator/pkg.yaml
  pkgs/ozankasikci/dockerfile-generator/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3435 feat: add rogerwelin/cassowary
  pkgs/rogerwelin/cassowary/pkg.yaml
  pkgs/rogerwelin/cassowary/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3437 fix: support TimothyYe/skm <= v0.8.5
  pkgs/TimothyYe/skm/pkg.yaml
  pkgs/TimothyYe/skm/registry.yaml
  registry.json
  registry.yaml
Labels: bug

#3525 feat: add 1xyz/pryrite
  pkgs/1xyz/pryrite/pkg.yaml
  pkgs/1xyz/pryrite/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3542 feat: support getting kubernetes/kubectl version from kubernetes/kubernetes
  pkgs/kubernetes/kubectl/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3546 feat: add sigstore/gitsign
  pkgs/sigstore/gitsign/pkg.yaml
  pkgs/sigstore/gitsign/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3577 docs: fix typo
  README.md
Labels: documentation

#3609 feat: add sethvargo/ratchet
  pkgs/sethvargo/ratchet/pkg.yaml
  pkgs/sethvargo/ratchet/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3631 feat: add doitintl/kube-no-trouble
  pkgs/doitintl/kube-no-trouble/pkg.yaml
  pkgs/doitintl/kube-no-trouble/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3636 feat: add datastax-labs/astra-cli
  pkgs/datastax-labs/astra-cli/pkg.yaml
  pkgs/datastax-labs/astra-cli/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3671 feat: add yohamta/dagu
  pkgs/yohamta/dagu/pkg.yaml
  pkgs/yohamta/dagu/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3672 feat: add uw-labs/strongbox
  pkgs/uw-labs/strongbox/pkg.yaml
  pkgs/uw-labs/strongbox/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3705 feat: add zix99/rare
  pkgs/zix99/rare/pkg.yaml
  pkgs/zix99/rare/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3706 feat: add hashicorp/terraform-plugin-docs
  pkgs/hashicorp/terraform-plugin-docs/pkg.yaml
  pkgs/hashicorp/terraform-plugin-docs/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3712 feat: add vmware-tanzu/octant
  pkgs/vmware-tanzu/octant/pkg.yaml
  pkgs/vmware-tanzu/octant/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3715 feat: add livebud/bud
  pkgs/livebud/bud/pkg.yaml
  pkgs/livebud/bud/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3713 feat: add go type packages
  .github/workflows/test.yaml
  pkgs/anqiansong/github-compare/pkg.yaml
  pkgs/anqiansong/github-compare/registry.yaml
  pkgs/golang/tools/gopls/pkg.yaml
  pkgs/golang/tools/gopls/registry.yaml
  pkgs/google/wire/pkg.yaml
  pkgs/google/wire/registry.yaml
  pkgs/katbyte/terrafmt/pkg.yaml
  pkgs/katbyte/terrafmt/registry.yaml
  pkgs/mitchellh/gox/pkg.yaml
  pkgs/mitchellh/gox/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3727 feat: add `denisidoro/navi`
  pkgs/denisidoro/navi/pkg.yaml
  pkgs/denisidoro/navi/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement
