Repository aquaproj/aqua-registry, pull requests merged in 2022-09, with the labels that each got.

#5908 fix(k1LoW/octocov): fix checksum file name
  pkgs/k1LoW/octocov/pkg.yaml
  pkgs/k1LoW/octocov/registry.yaml
  registry.yaml
Labels: bug

#5909 feat: add svenstaro/genact
  pkgs/svenstaro/genact/pkg.yaml
  pkgs/svenstaro/genact/registry.yaml
  registry.yaml
Labels: enhancement

#5936 feat: add climech/grit
  pkgs/climech/grit/pkg.yaml
  pkgs/climech/grit/registry.yaml
  registry.yaml
Labels: enhancement

#5938 feat: add clok/sm
  pkgs/clok/sm/pkg.yaml
  pkgs/clok/sm/registry.yaml
  registry.yaml
Labels: enhancement

#5937 feat: add gogs/gogs
  pkgs/gogs/gogs/pkg.yaml
  pkgs/gogs/gogs/registry.yaml
  registry.yaml
Labels: enhancement

#5948 feat: add cybozu/assam
  pkgs/cybozu/assam/pkg.yaml
  pkgs/cybozu/assam/registry.yaml
  registry.yaml
Labels: enhancement

#5949 feat: add lindell/multi-gitter
  pkgs/lindell/multi-gitter/pkg.yaml
  pkgs/lindell/multi-gitter/registry.yaml
  registry.yaml
Labels: enhancement

#5950 feat: add hherman1/gq
  pkgs/hherman1/gq/pkg.yaml
  pkgs/hherman1/gq/registry.yaml
  registry.yaml
Labels: enhancement

#5956 feat: add commercialhaskell/stack
  pkgs/commercialhaskell/stack/pkg.yaml
  pkgs/commercialhaskell/stack/registry.yaml
  registry.yaml
Labels: enhancement

#5971 feat: add crazy-max/diun
  pkgs/crazy-max/diun/pkg.yaml
  pkgs/crazy-max/diun/registry.yaml
  registry.yaml
Labels: enhancement

#5972 feat: add golang.org/x/tools/cmd/stringer
  pkgs/golang/tools/stringer/pkg.yaml
  pkgs/golang/tools/stringer/registry.yaml
  registry.yaml
Labels: enhancement

#5974 feat: add golang/tools/gorename
  pkgs/golang/tools/gorename/pkg.yaml
  pkgs/golang/tools/gorename/registry.yaml
  registry.yaml
Labels: enhancement

#5975 feat: add golang/tools/guru
  pkgs/golang/tools/guru/pkg.yaml
  pkgs/golang/tools/guru/registry.yaml
  registry.yaml
Labels: enhancement

#5977 feat: add golang/tools/godoc
  pkgs/golang/tools/godoc/pkg.yaml
  pkgs/golang/tools/godoc/registry.yaml
  registry.yaml
Labels: enhancement

#5990 feat: add Shopify/toxiproxy
  pkgs/Shopify/toxiproxy/pkg.yaml
  pkgs/Shopify/toxiproxy/registry.yaml
  registry.yaml
Labels: enhancement

#5991 feat: add mumoshu/conflint
  pkgs/mumoshu/conflint/pkg.yaml
  pkgs/mumoshu/conflint/registry.yaml
  registry.yaml
Labels: enhancement

#5992 feat: add crazy-max/ftpgrab
  pkgs/crazy-max/ftpgrab/pkg.yaml
  pkgs/crazy-max/ftpgrab/registry.yaml
  registry.yaml
Labels: enhancement

#5993 feat: add cloudquery/cloudquery
  pkgs/cloudquery/cloudquery/pkg.yaml
  pkgs/cloudquery/cloudquery/registry.yaml
  registry.yaml
Labels: enhancement

#6007 feat: add nuclio/nuclio
  pkgs/nuclio/nuclio/pkg.yaml
  pkgs/nuclio/nuclio/registry.yaml
  registry.yaml
Labels: enhancement

#6010 feat: add nao1215/gup
  pkgs/nao1215/gup/pkg.yaml
  pkgs/nao1215/gup/registry.yaml
  registry.yaml
Labels: enhancement

#6011 feat/rossmacarthur/sheldon
  pkgs/rossmacarthur/sheldon/pkg.yaml
  pkgs/rossmacarthur/sheldon/registry.yaml
  registry.yaml
Labels: enhancement

#6012 feat: add upx/upx
  pkgs/upx/upx/pkg.yaml
  pkgs/upx/upx/registry.yaml
  registry.yaml
Labels: enhancement

#6033 fix(ktock/buildg): set version_overrides
  pkgs/ktock/buildg/pkg.yaml
  pkgs/ktock/buildg/registry.yaml
  registry.yaml
Labels: bug

#6034 feat: add Songmu/tagpr
  pkgs/Songmu/tagpr/pkg.yaml
  pkgs/Songmu/tagpr/registry.yaml
  registry.yaml
Labels: enhancement

#6035 feat: add mmarkdown/mmark
  pkgs/mmarkdown/mmark/pkg.yaml
  pkgs/mmarkdown/mmark/registry.yaml
  registry.yaml
Labels: enhancement

#6089 fix(pulumi/kubespy): set version_overrides
  pkgs/pulumi/kubespy/pkg.yaml
  pkgs/pulumi/kubespy/registry.yaml
  registry.yaml
Labels: bug

#6093 fix(svenstaro/genact): set version_overrides
  pkgs/svenstaro/genact/pkg.yaml
  pkgs/svenstaro/genact/registry.yaml
  registry.yaml
Labels: bug

#6088 feat: add NathanBaulch/rainbow-roads
  pkgs/NathanBaulch/rainbow-roads/pkg.yaml
  pkgs/NathanBaulch/rainbow-roads/registry.yaml
  registry.yaml
Labels: enhancement

#6098 feat: add EdenEast/repo
  pkgs/EdenEast/repo/pkg.yaml
  pkgs/EdenEast/repo/registry.yaml
  registry.yaml
Labels: enhancement

#6115 feat: add Songmu/gh2changelog
  pkgs/Songmu/gh2changelog/pkg.yaml
  pkgs/Songmu/gh2changelog/registry.yaml
  registry.yaml
Labels: enhancement

#6155 feat: add inlets/mixctl
  pkgs/inlets/mixctl/pkg.yaml
  pkgs/inlets/mixctl/registry.yaml
  registry.yaml
Labels: enhancement

#6156 feat: add maxpert/marmot
  pkgs/maxpert/marmot/pkg.yaml
  pkgs/maxpert/marmot/registry.yaml
  registry.yaml
Labels: enhancement

#6158 feat: add mattermost/mmctl
  pkgs/mattermost/mmctl/pkg.yaml
  pkgs/mattermost/mmctl/registry.yaml
  registry.yaml
Labels: enhancement

#6159 feat: add JanDeDobbeleer/oh-my-posh
  pkgs/JanDeDobbeleer/oh-my-posh/pkg.yaml
  pkgs/JanDeDobbeleer/oh-my-posh/registry.yaml
  registry.yaml
Labels: enhancement

#6193 fix(Azure/aztfy): support aztfy >= 0.7.0
  pkgs/Azure/aztfy/pkg.yaml
  pkgs/Azure/aztfy/registry.yaml
  registry.yaml
Labels: bug

#6188 feat: add awslabs/yesiscan
  pkgs/awslabs/yesiscan/pkg.yaml
  pkgs/awslabs/yesiscan/registry.yaml
  registry.yaml
Labels: enhancement

#6186 feat: add gotify/cli
  pkgs/gotify/cli/pkg.yaml
  pkgs/gotify/cli/registry.yaml
  registry.yaml
Labels: enhancement

#6185 feat: add juicedata/juicefs
  pkgs/juicedata/juicefs/pkg.yaml
  pkgs/juicedata/juicefs/registry.yaml
  registry.yaml
Labels: enhancement

#6218 feat: add getgauge/gauge
  pkgs/getgauge/gauge/pkg.yaml
  pkgs/getgauge/gauge/registry.yaml
  registry.yaml
Labels: enhancement

#6219 feat: add awslabs/kubernetes-iteration-toolkit
  pkgs/awslabs/kubernetes-iteration-toolkit/pkg.yaml
  pkgs/awslabs/kubernetes-iteration-toolkit/registry.yaml
  registry.yaml
Labels: enhancement

#6220 feat: add grafana/jsonnet-language-server
  pkgs/grafana/jsonnet-language-server/pkg.yaml
  pkgs/grafana/jsonnet-language-server/registry.yaml
  registry.yaml
Labels: enhancement

#6244 fix(pulumi/pulumi): support >= 3.39.4
  pkgs/pulumi/pulumi/pkg.yaml
  pkgs/pulumi/pulumi/registry.yaml
  registry.yaml
Labels: bug

#6249 feat: add tdewolff/minify
  pkgs/tdewolff/minify/pkg.yaml
  pkgs/tdewolff/minify/registry.yaml
  registry.yaml
Labels: enhancement

#6279 fix(gohugoio/hugo): support hugo >= v0.103.0
  pkgs/gohugoio/hugo/pkg.yaml
  pkgs/gohugoio/hugo/registry.yaml
  registry.yaml
Labels: bug

#6276 feat: add ory/hydra
  pkgs/ory/hydra/pkg.yaml
  pkgs/ory/hydra/registry.yaml
  registry.yaml
Labels: enhancement

#6281 feat: add haveyoudebuggedit/gotestfmt
  pkgs/haveyoudebuggedit/gotestfmt/pkg.yaml
  pkgs/haveyoudebuggedit/gotestfmt/registry.yaml
  registry.yaml
Labels: enhancement

#6282 feat: add container-tools/spectrum
  pkgs/container-tools/spectrum/pkg.yaml
  pkgs/container-tools/spectrum/registry.yaml
  registry.yaml
Labels: enhancement

#6283 feat: add elkowar/pipr
  pkgs/elkowar/pipr/pkg.yaml
  pkgs/elkowar/pipr/registry.yaml
  registry.yaml
Labels: enhancement

#6292 fix(stackrox/kube-linter): support kube-linter >= v0.5.0
  pkgs/stackrox/kube-linter/pkg.yaml
  pkgs/stackrox/kube-linter/registry.yaml
  registry.yaml
Labels: bug

#6296 feat: add BishopFox/cloudfox
  pkgs/BishopFox/cloudfox/pkg.yaml
  pkgs/BishopFox/cloudfox/registry.yaml
  registry.yaml
Labels: enhancement

#6304 Add docker-credential-gcloud binary in twistedpair/google-cloud-sdk
  pkgs/twistedpair/google-cloud-sdk/registry.yaml
  registry.yaml
Labels: enhancement

#6305 feat(twistedpair/google-cloud-sdk): add a link to bq
  pkgs/twistedpair/google-cloud-sdk/registry.yaml
  registry.yaml
Labels: enhancement

#6309 feat: add golang/vuln/govulncheck
  pkgs/golang/vuln/govulncheck/pkg.yaml
  pkgs/golang/vuln/govulncheck/registry.yaml
  registry.yaml
Labels: enhancement

#6328 feat: add allero-io/allero
  pkgs/allero-io/allero/pkg.yaml
  pkgs/allero-io/allero/registry.yaml
  registry.yaml
Labels: enhancement

#6350 fix(webdevops/go-crond): support go-crond >= 22.9.0
  pkgs/webdevops/go-crond/pkg.yaml
  pkgs/webdevops/go-crond/registry.yaml
  registry.yaml
Labels: bug

#6346 feat: add gardener/docforge
  pkgs/gardener/docforge/pkg.yaml
  pkgs/gardener/docforge/registry.yaml
  registry.yaml
Labels: enhancement

#6347 fix(gleam-lang/gleam): support v0.23.0
  pkgs/gleam-lang/gleam/pkg.yaml
  pkgs/gleam-lang/gleam/registry.yaml
  registry.yaml
Labels: bug

#6373 feat: add bonnefoa/kubectl-fzf
  pkgs/bonnefoa/kubectl-fzf/pkg.yaml
  pkgs/bonnefoa/kubectl-fzf/registry.yaml
  registry.yaml
Labels: enhancement

#6381 feat: add noahgorstein/jqp
  pkgs/noahgorstein/jqp/pkg.yaml
  pkgs/noahgorstein/jqp/registry.yaml
  registry.yaml
Labels: enhancement

#6372 feat: add pseudomuto/protoc-gen-doc
  pkgs/pseudomuto/protoc-gen-doc/pkg.yaml
  pkgs/pseudomuto/protoc-gen-doc/registry.yaml
  registry.yaml
Labels: enhancement

#6390 feat: add k1LoW/ndiag
  pkgs/k1LoW/ndiag/pkg.yaml
  pkgs/k1LoW/ndiag/registry.yaml
  registry.yaml
Labels: enhancement

#6415 feat: add k1LoW/runn
  pkgs/k1LoW/runn/pkg.yaml
  pkgs/k1LoW/runn/registry.yaml
  registry.yaml
Labels: enhancement

#6417 feat: add snyk/cli
  pkgs/snyk/cli/pkg.yaml
  pkgs/snyk/cli/registry.yaml
  registry.yaml
Labels: enhancement

#6418 feat: add ryodocx/kube-credential-cache
  pkgs/ryodocx/kube-credential-cache/pkg.yaml
  pkgs/ryodocx/kube-credential-cache/registry.yaml
  registry.yaml
Labels: enhancement

#6477 feat: add ilaif/goplicate
  pkgs/ilaif/goplicate/pkg.yaml
  pkgs/ilaif/goplicate/registry.yaml
  registry.yaml
Labels: enhancement

#6500 docs: add a link to oss-contribution-guide
  CONTRIBUTING.md
Labels: documentation

#6515 feat: add Songmu/maltmill
  pkgs/Songmu/maltmill/pkg.yaml
  pkgs/Songmu/maltmill/registry.yaml
  registry.yaml
Labels: enhancement

#6516 chore: Some fixes to `x-motemen/ghq`
  pkgs/x-motemen/ghq/registry.yaml
  registry.yaml
Labels: bug

#6573 fix(editorconfig-checker/editorconfig-checker): fix to support 2.6.0
  pkgs/editorconfig-checker/editorconfig-checker/pkg.yaml
  pkgs/editorconfig-checker/editorconfig-checker/registry.yaml
  registry.yaml
Labels: bug

#6570 feat: add shenwei356/csvtk
  pkgs/shenwei356/csvtk/pkg.yaml
  pkgs/shenwei356/csvtk/registry.yaml
  registry.yaml
Labels: enhancement

#6604 fix(kvz/json2hcl): set version_overrides to support old versions
  pkgs/kvz/json2hcl/pkg.yaml
  pkgs/kvz/json2hcl/registry.yaml
  registry.yaml
Labels: bug

#6606 fix(helm/helm): support old versions on darwin/arm64
  pkgs/helm/helm/pkg.yaml
  pkgs/helm/helm/registry.yaml
  registry.yaml
Labels: bug

#6612 fix(helm/helm): fix checksum config to support old versions
  pkgs/helm/helm/pkg.yaml
  pkgs/helm/helm/registry.yaml
  registry.yaml
Labels: bug

#6611 feat: add grafana/xk6
  pkgs/grafana/xk6/pkg.yaml
  pkgs/grafana/xk6/registry.yaml
  registry.yaml
Labels: enhancement

#6618 fix(kubernetes/kubectl): enable rosetta2 in case of kubectl < v1.21.0
  pkgs/kubernetes-sigs/kustomize/registry.yaml
  pkgs/kubernetes/kubectl/pkg.yaml
  pkgs/kubernetes/kubectl/registry.yaml
  registry.yaml
Labels: bug

#6619 fix(drlau/akashi): set version_overrides to support old versions
  pkgs/drlau/akashi/pkg.yaml
  pkgs/drlau/akashi/registry.yaml
  registry.yaml
Labels: bug

#6620 fix(reviewdog/reviewdog): set version_overrides
  pkgs/reviewdog/reviewdog/pkg.yaml
  pkgs/reviewdog/reviewdog/registry.yaml
  registry.yaml
Labels: bug

#6621 fix(mikefarah/yq): set version_overrides
  pkgs/mikefarah/yq/pkg.yaml
  pkgs/mikefarah/yq/registry.yaml
  registry.yaml
Labels: bug

#6670 feat: add dtan4/k8sec
  pkgs/dtan4/k8sec/pkg.yaml
  pkgs/dtan4/k8sec/registry.yaml
  registry.yaml
Labels: enhancement

#6671 feat: add dtan4/s3url
  pkgs/dtan4/s3url/pkg.yaml
  pkgs/dtan4/s3url/registry.yaml
  registry.yaml
Labels: enhancement

#6673 feat: add mashiike/stefunny
  pkgs/mashiike/stefunny/pkg.yaml
  pkgs/mashiike/stefunny/registry.yaml
  registry.yaml
Labels: enhancement
