Repository aquaproj/aqua-registry, pull requests merged in 2022-10, with the labels that each got.

#6704 feat: rename roboll/helmfile to helmfile/helmfile
  pkgs/helmfile/helmfile/pkg.yaml
  pkgs/helmfile/helmfile/registry.yaml
  pkgs/roboll/helmfile/pkg.yaml
  pkgs/roboll/helmfile/registry.yaml
  registry.yaml
Labels: enhancement

#6705 feat: add kevincobain2000/gobrew
  pkgs/kevincobain2000/gobrew/pkg.yaml
  pkgs/kevincobain2000/gobrew/registry.yaml
  registry.yaml
Labels: enhancement

#6709 fix(kurehajime/dajarep): fix checksum config
  pkgs/kurehajime/dajarep/registry.yaml
  registry.yaml
Labels: bug

#6712 feat: add takumin/gjson
  pkgs/takumin/gjson/pkg.yaml
  pkgs/takumin/gjson/registry.yaml
  registry.yaml
Labels: enhancement

#6729 fix(junegunn/fzf): disable checksum for darwin
  .github/workflows/test.yaml
  pkgs/junegunn/fzf/registry.yaml
  registry.yaml
Labels: bug

#6730 feat: add kcp-dev/kcp
  pkgs/kcp-dev/kcp/kubectl-kcp/pkg.yaml
  pkgs/kcp-dev/kcp/kubectl-kcp/registry.yaml
  pkgs/kcp-dev/kcp/pkg.yaml
  pkgs/kcp-dev/kcp/registry.yaml
  registry.yaml
Labels: enhancement

#6737 fix(junegunn/fzf): set version_overrides
  pkgs/junegunn/fzf/pkg.yaml
  pkgs/junegunn/fzf/registry.yaml
  registry.yaml
Labels: bug

#6766 fix(alexellis/k3sup): fix checksum config
  pkgs/alexellis/k3sup/registry.yaml
  registry.yaml
Labels: bug

#6768 fix(shipyard-run/shipyard): fix checksum config
  pkgs/shipyard-run/shipyard/pkg.yaml
  pkgs/shipyard-run/shipyard/registry.yaml
  registry.yaml
Labels: bug

#6769 fix(hktalent/scan4all): fix checksum config
  pkgs/hktalent/scan4all/registry.yaml
  registry.yaml
Labels: bug

#6779 fix(neovim/neovim): fix checksum config
  pkgs/neovim/neovim/registry.yaml
  registry.yaml
Labels: bug

#6781 fix(hairyhenderson/gomplate): fix checksum config
  pkgs/hairyhenderson/gomplate/registry.yaml
  registry.yaml
Labels: bug

#6782 fix: fix checksum config (corneliusweig/*)
  pkgs/corneliusweig/ketall/registry.yaml
  pkgs/corneliusweig/rakkess/access-matrix/registry.yaml
  pkgs/corneliusweig/rakkess/registry.yaml
  registry.yaml
Labels: bug

#6784 fix(siderolabs/talos): fix checksum
  pkgs/siderolabs/talos/registry.yaml
  registry.yaml
Labels: bug

#6793 feat: add fullstorydev/grpcui
  pkgs/fullstorydev/grpcui/pkg.yaml
  pkgs/fullstorydev/grpcui/registry.yaml
  registry.yaml
Labels: enhancement

#6800 fix(harness/drone-cli): fix checksum config
  pkgs/harness/drone-cli/registry.yaml
  registry.yaml
Labels: bug

#6808 fix(genuinetools): fix checksum config
  pkgs/genuinetools/img/registry.yaml
  pkgs/genuinetools/reg/registry.yaml
  registry.yaml
Labels: bug

#6809 fix(loft-sh/devspace): fix checksum config
  pkgs/loft-sh/devspace/registry.yaml
  registry.yaml
Labels: bug

#6810 fix(siderolabs/conform): fix checksum config
  pkgs/siderolabs/conform/registry.yaml
  registry.yaml
Labels: bug

#6811 fix(okteto/okteto): fix checksum config
  pkgs/okteto/okteto/registry.yaml
  registry.yaml
Labels: bug

#6817 fix(openfaas/faas-cli): fix checksum config
  pkgs/openfaas/faas-cli/registry.yaml
  registry.yaml
Labels: bug

#6819 fix(quarkslab/kdigger): change format to "raw" and fix checksum
  pkgs/quarkslab/kdigger/registry.yaml
  registry.yaml
Labels: bug

#6820 fix(particledecay/kconf): fix replacements
  pkgs/particledecay/kconf/registry.yaml
  registry.yaml
Labels: bug

#6825 fix(barnybug/cli53): fix checksum config
  pkgs/barnybug/cli53/registry.yaml
  registry.yaml
Labels: bug

#6826 fix(kool-dev/kool): fix checksum config
  pkgs/kool-dev/kool/registry.yaml
  registry.yaml
Labels: bug

#6827 fix(cnrancher/autok3s): fix checksum config
  pkgs/cnrancher/autok3s/registry.yaml
  registry.yaml
Labels: bug

#6828 fix(ddosify/ddosify): fix asset name
  pkgs/ddosify/ddosify/registry.yaml
  registry.yaml
Labels: bug

#6829 fix(alexellis/arkade): fix checksum config
  pkgs/alexellis/arkade/registry.yaml
  registry.yaml
Labels: bug

#6830 fix(Traackr/binnacle): fix checksum config
  pkgs/Traackr/binnacle/registry.yaml
  registry.yaml
Labels: bug

#6831 fix(zellij-org/zellij): disable checksum
  pkgs/zellij-org/zellij/registry.yaml
  registry.yaml
Labels: bug

#6832 fix(inlets/inletsctl): disable checksum
  pkgs/inlets/inletsctl/registry.yaml
  registry.yaml
Labels: bug

#6833 fix(inlets/inlets-pro): fix checksum config
  pkgs/inlets/inlets-pro/registry.yaml
  registry.yaml
Labels: bug

#6834 fix(docker/compose): fix checksum config
  pkgs/docker/compose/pkg.yaml
  pkgs/docker/compose/registry.yaml
  registry.yaml
Labels: bug

#6835 fix(anchore/syft): fix checksum config
  pkgs/anchore/syft/pkg.yaml
  pkgs/anchore/syft/registry.yaml
  registry.yaml
Labels: bug

#6852 fix(kcp-dev/kcp/kubectl-kcp): support >= v0.9.0
  pkgs/kcp-dev/kcp/kubectl-kcp/pkg.yaml
  pkgs/kcp-dev/kcp/kubectl-kcp/registry.yaml
  pkgs/kcp-dev/kcp/pkg.yaml
  registry.yaml
Labels: bug

#6846 feat: add grpc-ecosystem/grpc-health-probe
  pkgs/grpc-ecosystem/grpc-health-probe/pkg.yaml
  pkgs/grpc-ecosystem/grpc-health-probe/registry.yaml
  registry.yaml
Labels: enhancement

#6883 feat: add smallstep/cli
  pkgs/smallstep/cli/pkg.yaml
  pkgs/smallstep/cli/registry.yaml
  registry.yaml
Labels: enhancement

#6889 feat: add git-town
  pkgs/git-town/git-town/pkg.yaml
  pkgs/git-town/git-town/registry.yaml
  registry.yaml
Labels: enhancement

#6892 feat: add thycotic/dsv-cli
  pkgs/thycotic/dsv-cli/pkg.yaml
  pkgs/thycotic/dsv-cli/registry.yaml
  registry.yaml
Labels: enhancement

#6909 feat: add hashicorp/packer-plugin-sdk/packer-sdc
  pkgs/hashicorp/packer-plugin-sdk/packer-sdc/pkg.yaml
  pkgs/hashicorp/packer-plugin-sdk/packer-sdc/registry.yaml
  registry.yaml
Labels: enhancement

#6860 fix(thought-machine/please): fix checksum config
  pkgs/thought-machine/please/registry.yaml
  registry.yaml
Labels: bug

#6914 fix(ipfs/kubo): fix checksum config
  pkgs/ipfs/kubo/registry.yaml
  registry.yaml
Labels: bug

#6917 fix(haveyoudebuggedit/gotestfmt): rename the package to `GoTestTools/gotestfmt`
  pkgs/GoTestTools/gotestfmt/pkg.yaml
  pkgs/GoTestTools/gotestfmt/registry.yaml
  pkgs/haveyoudebuggedit/gotestfmt/pkg.yaml
  registry.yaml
Labels: bug

#6955 feat: add fujiwara/ecsta
  pkgs/fujiwara/ecsta/pkg.yaml
  pkgs/fujiwara/ecsta/registry.yaml
  registry.yaml
Labels: enhancement

#6990 fix(pivotal-cf/om): support 7.8.0
  pkgs/pivotal-cf/om/pkg.yaml
  pkgs/pivotal-cf/om/registry.yaml
  registry.yaml
Labels: bug

#6999 fix(bep/s3deploy): support v2.9.0
  pkgs/bep/s3deploy/pkg.yaml
  pkgs/bep/s3deploy/registry.yaml
  registry.yaml
Labels: bug

#7028 fix(Aloxaf/silicon): remove windows/amd64 from v0.5.0
  pkgs/Aloxaf/silicon/registry.yaml
  registry.yaml
Labels: bug

#7033 fix(cert-manager/cert-manager/cmctl): fix the package name
  pkgs/cert-manager/cert-manager/cmctl/registry.yaml
  registry.yaml
Labels: bug

#7066 fix(Aloxaf/silicon): support v0.5.1 in windows
  pkgs/Aloxaf/silicon/pkg.yaml
  pkgs/Aloxaf/silicon/registry.yaml
  registry.yaml
Labels: bug

#7071 feat: add containers/crun
  pkgs/containers/crun/pkg.yaml
  pkgs/containers/crun/registry.yaml
  registry.yaml
Labels: enhancement

#7070 feat: add containers/fuse-overlayfs
  pkgs/containers/fuse-overlayfs/pkg.yaml
  pkgs/containers/fuse-overlayfs/registry.yaml
  registry.yaml
Labels: enhancement

#7067 feat: add rootless-containers/rootlesskit
  pkgs/rootless-containers/rootlesskit/pkg.yaml
  pkgs/rootless-containers/rootlesskit/registry.yaml
  registry.yaml
Labels: enhancement

#7068 feat: add rootless-containers/slirp4netns
  pkgs/rootless-containers/slirp4netns/pkg.yaml
  pkgs/rootless-containers/slirp4netns/registry.yaml
  registry.yaml
Labels: enhancement

#7081 feat: add containerd/containerd
  pkgs/containerd/containerd/pkg.yaml
  pkgs/containerd/containerd/registry.yaml
  registry.yaml
Labels: enhancement

#7086 feat: add kubernetes/kubectl-convert
  pkgs/kubernetes/kubectl-convert/pkg.yaml
  pkgs/kubernetes/kubectl-convert/registry.yaml
  registry.yaml
Labels: enhancement

#7087 feat: add kubernetes/kubeadm
  pkgs/kubernetes/kubeadm/pkg.yaml
  pkgs/kubernetes/kubeadm/registry.yaml
  registry.yaml
Labels: enhancement

#7083 feat: add opencontainers/runc
  pkgs/opencontainers/runc/pkg.yaml
  pkgs/opencontainers/runc/registry.yaml
  registry.yaml
Labels: enhancement

#7089 feat: add NetApp/trident/tridentctl
  pkgs/NetApp/trident/tridentctl/pkg.yaml
  pkgs/NetApp/trident/tridentctl/registry.yaml
  registry.yaml
Labels: enhancement

#7092 feat: add goccy/bigquery-emulator
  pkgs/goccy/bigquery-emulator/pkg.yaml
  pkgs/goccy/bigquery-emulator/registry.yaml
  registry.yaml
Labels: enhancement

#7095 feat: add hashicorp/boundary
  pkgs/hashicorp/boundary/pkg.yaml
  pkgs/hashicorp/boundary/registry.yaml
  registry.yaml
Labels: enhancement

#7096 feat: add GoogleCloudPlatform/cloud-sql-proxy
  pkgs/GoogleCloudPlatform/cloud-sql-proxy/pkg.yaml
  pkgs/GoogleCloudPlatform/cloud-sql-proxy/registry.yaml
  registry.yaml
Labels: enhancement

#7084 feat: add containerd/fuse-overlayfs-snapshotter
  pkgs/containerd/fuse-overlayfs-snapshotter/pkg.yaml
  pkgs/containerd/fuse-overlayfs-snapshotter/registry.yaml
  registry.yaml
Labels: enhancement

#7114 fix(kubevela/kubevela/kubectl-plugin): enable checksum verification
  pkgs/kubevela/kubevela/kubectl-plugin/pkg.yaml
  pkgs/kubevela/kubevela/kubectl-plugin/registry.yaml
  registry.yaml
Labels: bug

#7115 fix(kubevela/kubevela): enable checksum verification
  pkgs/kubevela/kubevela/pkg.yaml
  pkgs/kubevela/kubevela/registry.yaml
  registry.yaml
Labels: bug

#7148 fix(ossf/scorecard): disable checkum for linux/amd64 v4.4.0
  pkgs/ossf/scorecard/registry.yaml
  registry.yaml
Labels: bug

#7149 fix(argoproj/argo-cd): support v2.4.15
  pkgs/argoproj/argo-cd/pkg.yaml
  pkgs/argoproj/argo-cd/registry.yaml
  registry.yaml
Labels: bug

#7146 fix(git-town): 🐛 package did not handle replacements for cpu type correctly
  pkgs/git-town/git-town/pkg.yaml
  pkgs/git-town/git-town/registry.yaml
  registry.yaml
Labels: bug

#7156 fix(dalance/procs): fix windows files to support v0.13.3 or later
  pkgs/dalance/procs/pkg.yaml
  pkgs/dalance/procs/registry.yaml
  registry.yaml
Labels: bug

#7158 feat: add slsa-framework/slsa-github-generator/slsa-builder-go
  .github/workflows/test.yaml
  pkgs/slsa-framework/slsa-github-generator/slsa-builder-go/pkg.yaml
  pkgs/slsa-framework/slsa-github-generator/slsa-builder-go/registry.yaml
  registry.yaml
Labels: enhancement

#7157 feat(slsa-framework/slsa-verifier): support platform other than linux/amd64 with `go_install` package
  pkgs/slsa-framework/slsa-verifier/registry.yaml
  registry.yaml
Labels: enhancement

#7159 feat: add hirose31/s3surfer
  pkgs/hirose31/s3surfer/pkg.yaml
  pkgs/hirose31/s3surfer/registry.yaml
  registry.yaml
Labels: enhancement

#7161 feat: add koluku/s3s
  pkgs/koluku/s3s/pkg.yaml
  pkgs/koluku/s3s/registry.yaml
  registry.yaml
Labels: enhancement

#7167 fix(slsa-framework/slsa-github-generator/slsa-builder-go): fix the description
  pkgs/slsa-framework/slsa-github-generator/slsa-builder-go/registry.yaml
  registry.yaml
Labels: bug

#7177 feat: add volta-cli/volta
  pkgs/volta-cli/volta/pkg.yaml
  pkgs/volta-cli/volta/registry.yaml
  registry.yaml
Labels: enhancement

#7179 feat: add dylanaraps/neofetch
  pkgs/dylanaraps/neofetch/pkg.yaml
  pkgs/dylanaraps/neofetch/registry.yaml
  registry.yaml
Labels: enhancement

#7180 feat: add dbrgn/tealdeer
  pkgs/dbrgn/tealdeer/pkg.yaml
  pkgs/dbrgn/tealdeer/registry.yaml
  registry.yaml
Labels: enhancement

#7209 fix(aquasecurity/starboard): support >= v0.15.0
  pkgs/aquasecurity/starboard/registry.yaml
  registry.yaml
Labels: bug

#7208 feat: add k1LoW/awsdo
  pkgs/k1LoW/awsdo/pkg.yaml
  pkgs/k1LoW/awsdo/registry.yaml
  registry.yaml
Labels: enhancement

#7216 feat: add kyverno/kyverno
  pkgs/kyverno/kyverno/pkg.yaml
  pkgs/kyverno/kyverno/registry.yaml
  registry.yaml
Labels: enhancement

#7290 feat: add Azure/draft
  pkgs/Azure/draft/pkg.yaml
  pkgs/Azure/draft/registry.yaml
  registry.yaml
Labels: enhancement

#7317 feat: add bitwarden/clients
  pkgs/bitwarden/clients/pkg.yaml
  pkgs/bitwarden/clients/registry.yaml
  registry.yaml
Labels: enhancement

#7312 feat: add wakatime/wakatime-cli
  pkgs/wakatime/wakatime-cli/pkg.yaml
  pkgs/wakatime/wakatime-cli/registry.yaml
  registry.yaml
Labels: enhancement

#7320 feat: add handlename/ssmwrap
  pkgs/handlename/ssmwrap/pkg.yaml
  pkgs/handlename/ssmwrap/registry.yaml
  registry.yaml
Labels: enhancement

#7323 feat: add kyoshidajp/ghkw
  pkgs/kyoshidajp/ghkw/pkg.yaml
  pkgs/kyoshidajp/ghkw/registry.yaml
  registry.yaml
Labels: enhancement

#7353 feat: add ysugimoto/falco
  pkgs/ysugimoto/falco/pkg.yaml
  pkgs/ysugimoto/falco/registry.yaml
  registry.yaml
Labels: enhancement

#7386 feat: add drud/ddev
  pkgs/drud/ddev/pkg.yaml
  pkgs/drud/ddev/registry.yaml
  registry.yaml
Labels: enhancement

#7389 docs: add the description about issue
  CONTRIBUTING.md
Labels: documentation

#7388 feat: add librespeed/speedtest-cli
  pkgs/librespeed/speedtest-cli/pkg.yaml
  pkgs/librespeed/speedtest-cli/registry.yaml
  registry.yaml
Labels: enhancement

#7392 feat: add making/rsc
  pkgs/making/rsc/pkg.yaml
  pkgs/making/rsc/registry.yaml
  registry.yaml
Labels: enhancement

#7439 feat: add minamijoyo/myaws
  pkgs/minamijoyo/myaws/pkg.yaml
  pkgs/minamijoyo/myaws/registry.yaml
  registry.yaml
Labels: enhancement

#7446 feat: add purpleclay/dns53
  pkgs/purpleclay/dns53/pkg.yaml
  pkgs/purpleclay/dns53/registry.yaml
  registry.yaml
Labels: enhancement

#7466 feat: add charmbracelet/vhs
  pkgs/charmbracelet/vhs/pkg.yaml
  pkgs/charmbracelet/vhs/registry.yaml
  registry.yaml
Labels: enhancement

#7473 feat: add genuinetools/amicontained
  pkgs/genuinetools/amicontained/pkg.yaml
  pkgs/genuinetools/amicontained/registry.yaml
  registry.yaml
Labels: enhancement

#7486 feat: add runatlantis/atlantis
  pkgs/runatlantis/atlantis/pkg.yaml
  pkgs/runatlantis/atlantis/registry.yaml
  registry.yaml
Labels: enhancement

#7488 feat: add mitchellh/gon
  pkgs/mitchellh/gon/pkg.yaml
  pkgs/mitchellh/gon/registry.yaml
  registry.yaml
Labels: enhancement

#7495 feat: add sonatype-nexus-community/nancy
  pkgs/sonatype-nexus-community/nancy/pkg.yaml
  pkgs/sonatype-nexus-community/nancy/registry.yaml
  registry.yaml
Labels: enhancement
