Repository aquaproj/aqua-registry, pull requests merged in 2022-04, with the labels that each got.

#2777 fix: typo
  registry.yaml
Labels: bug, target:gleam-lang/gleam

#2780 Fix: correct some packages for arm64
  registry.yaml
Labels: target:dandavison/delta, target:lotabout/skim

#2781 Feat: Add sheepla/fzwiki and more
  pkgs/sheepla/fzwiki/pkg.yaml
  pkgs/sheepla/qiitaz/pkg.yaml
  pkgs/tomnomnom/gron/pkg.yaml
  registry.yaml
Labels: enhancement

#2782 fix: fix qiitaz
  registry.yaml
Labels: bug, target:sheepla/qiitaz

#2790 feat: add dagger/dagger
  .github/workflows/test.yaml
  pkgs/dagger/dagger/pkg.yaml
  pkgs/dagger/dagger/registry.yaml
  registry.yaml
Labels: enhancement

#2797 feat: Add ziglang/zig
  pkgs/ziglang/zig/pkg.yaml
  pkgs/ziglang/zig/registry.yaml
  registry.yaml
Labels: enhancement

#2862 feat: add trufflesecurity/trufflehog
  pkgs/trufflesecurity/trufflehog/pkg.yaml
  pkgs/trufflesecurity/trufflehog/registry.yaml
  registry.yaml
Labels: enhancement

#2863 feat: add s0md3v/Smap
  pkgs/s0md3v/Smap/pkg.yaml
  pkgs/s0md3v/Smap/registry.yaml
  registry.yaml
Labels: enhancement

#2872 add haskell ghcup and cabal-install
  pkgs/haskell/cabal/cabal-install/pkg.yaml
  pkgs/haskell/cabal/cabal-install/registry.yaml
  pkgs/haskell/ghcup-hs/pkg.yaml
  pkgs/haskell/ghcup-hs/registry.yaml
  registry.yaml
Labels: enhancement

#2894 feat: add suzuki-shunsuke/discussion-slack-notifier
  pkgs/suzuki-shunsuke/discussion-slack-notifier/pkg.yaml
  pkgs/suzuki-shunsuke/discussion-slack-notifier/registry.yaml
  registry.yaml
Labels: enhancement

#2946 feat: add gcla/termshark
  pkgs/gcla/termshark/pkg.yaml
  pkgs/gcla/termshark/registry.yaml
  registry.yaml
Labels: enhancement

#2947 fix: follow up #2946
  pkgs/gcla/termshark/registry.yaml
  registry.yaml
Labels: bug

#2974 feat: add Azure/aztfy
  pkgs/Azure/aztfy/pkg.yaml
  pkgs/Azure/aztfy/registry.yaml
  registry.yaml
Labels: enhancement

#2980 Add high-moctane/nextword
  pkgs/high-moctane/nextword/pkg.yaml
  pkgs/high-moctane/nextword/registry.yaml
  registry.yaml
Labels: enhancement

#2979 Add sumneko/lua-language-server
  pkgs/sumneko/lua-language-server/pkg.yaml
  pkgs/sumneko/lua-language-server/registry.yaml
  registry.yaml
Labels: enhancement

#3028 feat: `grpc-ecosystem/grpc-gateway`
  pkgs/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway/pkg.yaml
  pkgs/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway/registry.yaml
  pkgs/grpc-ecosystem/grpc-gateway/protoc-gen-openapiv2/pkg.yaml
  pkgs/grpc-ecosystem/grpc-gateway/protoc-gen-openapiv2/registry.yaml
  registry.yaml
Labels: enhancement

#3047 feat: `protocolbuffers/protobuf-go/protoc-gen-go`
  pkgs/protocolbuffers/protobuf-go/protoc-gen-go/pkg.yaml
  pkgs/protocolbuffers/protobuf-go/protoc-gen-go/registry.yaml
  registry.yaml
Labels: enhancement

#3048 feat: `dominikh/go-tools/staticcheck`
  pkgs/dominikh/go-tools/staticcheck/pkg.yaml
  pkgs/dominikh/go-tools/staticcheck/registry.yaml
  registry.yaml
Labels: enhancement

#3049 feat: `grpc/grpc-go/protoc-gen-go-grpc`
  pkgs/grpc/grpc-go/protoc-gen-go-grpc/pkg.yaml
  pkgs/grpc/grpc-go/protoc-gen-go-grpc/registry.yaml
  registry.yaml
Labels: enhancement

#3083 feat: add sqshq/sampler
  pkgs/sqshq/sampler/pkg.yaml
  pkgs/sqshq/sampler/registry.yaml
  registry.yaml
Labels: enhancement

#3109 feat: add suzuki-shunsuke/renovate-issue-action
  pkgs/suzuki-shunsuke/renovate-issue-action/pkg.yaml
  pkgs/suzuki-shunsuke/renovate-issue-action/registry.yaml
  registry.yaml
Labels: enhancement

#3157 feat: add ClementTsang/bottom
  pkgs/ClementTsang/bottom/pkg.yaml
  pkgs/ClementTsang/bottom/registry.yaml
  registry.yaml
Labels: enhancement

#3151 add evilmartians/lefthook
  pkgs/evilmartians/lefthook/pkg.yaml
  pkgs/evilmartians/lefthook/registry.yaml
  registry.yaml
Labels: enhancement

#3158 feat: add sharkdp/hyperfine
  pkgs/sharkdp/hyperfine/pkg.yaml
  pkgs/sharkdp/hyperfine/registry.yaml
  registry.yaml
Labels: enhancement

#3159 feat: add orf/gping
  pkgs/orf/gping/pkg.yaml
  pkgs/orf/gping/registry.yaml
  registry.yaml
Labels: enhancement

#3160 feat: add rs/curlie
  pkgs/rs/curlie/pkg.yaml
  pkgs/rs/curlie/registry.yaml
  registry.yaml
Labels: enhancement

#3168 feat: Add Aloxaf/silicon
  pkgs/Aloxaf/silicon/pkg.yaml
  pkgs/Aloxaf/silicon/registry.yaml
  registry.yaml
Labels: enhancement

#3224 chore: update talos-systems org rename
  pkgs/siderolabs/conform/pkg.yaml
  pkgs/siderolabs/conform/registry.yaml
  pkgs/siderolabs/talos/pkg.yaml
  pkgs/siderolabs/talos/registry.yaml
  pkgs/talos-systems/conform/pkg.yaml
  pkgs/talos-systems/talos/pkg.yaml
  registry.yaml
Labels: rename package

#3233 fix: recover talos-systems for compatibility
  pkgs/talos-systems/conform/pkg.yaml
  pkgs/talos-systems/conform/registry.yaml
  pkgs/talos-systems/talos/pkg.yaml
  pkgs/talos-systems/talos/registry.yaml
  registry.yaml
Labels: bug

#3237 feat: add bronze1man/yaml2json
  pkgs/bronze1man/yaml2json/pkg.yaml
  pkgs/bronze1man/yaml2json/registry.yaml
  registry.yaml
Labels: enhancement

#3238 feat: add theila
  pkgs/siderolabs/theila/pkg.yaml
  pkgs/siderolabs/theila/registry.yaml
  registry.yaml
Labels: enhancement
