Repository aquaproj/aqua-registry, pull requests merged in 2022-12, with the labels that each got.

#8212 feat: add livesense-inc/go-aws-s3get
  pkgs/livesense-inc/go-aws-s3get/pkg.yaml
  pkgs/livesense-inc/go-aws-s3get/registry.yaml
  registry.yaml
Labels: enhancement

#8248 feat: add anchore/quill
  pkgs/anchore/quill/pkg.yaml
  pkgs/anchore/quill/registry.yaml
  registry.yaml
Labels: enhancement

#8311 feat: add yitsushi/totp-cli
  pkgs/yitsushi/totp-cli/pkg.yaml
  pkgs/yitsushi/totp-cli/registry.yaml
  registry.yaml
Labels: enhancement

#8375 feat: add octohelm/cuemod
  pkgs/octohelm/cuemod/pkg.yaml
  pkgs/octohelm/cuemod/registry.yaml
  registry.yaml
Labels: enhancement

#8466 feat: add corrupt952/closest
  pkgs/corrupt952/closest/pkg.yaml
  pkgs/corrupt952/closest/registry.yaml
  registry.yaml
Labels: enhancement

#8497 fix(updatecli/updatecli): support v0.40.2
  pkgs/updatecli/updatecli/pkg.yaml
  pkgs/updatecli/updatecli/registry.yaml
  registry.yaml
Labels: bug

#8498 feat: add prometheus/promlens
  pkgs/prometheus/promlens/pkg.yaml
  pkgs/prometheus/promlens/registry.yaml
  registry.yaml
Labels: enhancement

#8578 fix(slsa-framework/slsa-verifier): fix Go Module Path to support v2
  pkgs/slsa-framework/slsa-verifier/pkg.yaml
  pkgs/slsa-framework/slsa-verifier/registry.yaml
  registry.yaml
Labels: bug

#8645 feat: add chenjiandongx/kubectl-images
  pkgs/chenjiandongx/kubectl-images/pkg.yaml
  pkgs/chenjiandongx/kubectl-images/registry.yaml
  registry.yaml
Labels: enhancement

#8651 fix(omrikiei/ktunnel) symlink kubectl-ktunnel
  pkgs/omrikiei/ktunnel/registry.yaml
  registry.yaml
Labels: bug

#8668 fix(x-motemen/blogsync): support v0.12.2
  pkgs/x-motemen/blogsync/pkg.yaml
  pkgs/x-motemen/blogsync/registry.yaml
  registry.yaml
Labels: bug

#8686 feat: add aquaproj/example-go-slsa-provenance and update tflint
  pkgs/aquaproj/example-go-slsa-provenance/pkg.yaml
  pkgs/aquaproj/example-go-slsa-provenance/registry.yaml
  pkgs/terraform-linters/tflint/registry.yaml
  registry.yaml
Labels: enhancement, security, cosign, slsa

#8689 feat: add ipinfo/cli and ipinfo/cli/{subcommand}
  pkgs/ipinfo/cli/cidr2ip/pkg.yaml
  pkgs/ipinfo/cli/cidr2ip/registry.yaml
  pkgs/ipinfo/cli/cidr2range/pkg.yaml
  pkgs/ipinfo/cli/cidr2range/registry.yaml
  pkgs/ipinfo/cli/grepip/pkg.yaml
  pkgs/ipinfo/cli/grepip/registry.yaml
  pkgs/ipinfo/cli/pkg.yaml
  pkgs/ipinfo/cli/prips/pkg.yaml
  pkgs/ipinfo/cli/prips/registry.yaml
  pkgs/ipinfo/cli/randip/pkg.yaml
  pkgs/ipinfo/cli/randip/registry.yaml
  pkgs/ipinfo/cli/range2cidr/pkg.yaml
  pkgs/ipinfo/cli/range2cidr/registry.yaml
  pkgs/ipinfo/cli/range2ip/pkg.yaml
  pkgs/ipinfo/cli/range2ip/registry.yaml
  pkgs/ipinfo/cli/registry.yaml
  pkgs/ipinfo/cli/splitcidr/pkg.yaml
  pkgs/ipinfo/cli/splitcidr/registry.yaml
  registry.yaml
Labels: enhancement

#8693 feat: add Songmu/timeout
  pkgs/Songmu/timeout/pkg.yaml
  pkgs/Songmu/timeout/registry.yaml
  registry.yaml
Labels: enhancement

#8696 feat: add wasmerio/wapm-cli
  pkgs/wasmerio/wapm-cli/pkg.yaml
  pkgs/wasmerio/wapm-cli/registry.yaml
  registry.yaml
Labels: enhancement

#8718 feat: add FairwindsOps/gonogo
  .github/workflows/test.yaml
  pkgs/FairwindsOps/gonogo/pkg.yaml
  pkgs/FairwindsOps/gonogo/registry.yaml
  registry.yaml
Labels: enhancement

#8731 feat(argoproj/argo-workflows): add cosign setting
  pkgs/argoproj/argo-workflows/registry.yaml
  registry.yaml
Labels: security, cosign

#8732 feat(updatecli/updatecli): add cosign setting
  pkgs/updatecli/updatecli/registry.yaml
  registry.yaml
Labels: security, cosign

#8742 feat: add Songmu/gitsemvers
  pkgs/Songmu/gitsemvers/pkg.yaml
  pkgs/Songmu/gitsemvers/registry.yaml
  registry.yaml
Labels: enhancement

#8743 feat: add mr-karan/doggo
  pkgs/mr-karan/doggo/pkg.yaml
  pkgs/mr-karan/doggo/registry.yaml
  registry.yaml
Labels: enhancement

#8757 feat: add spf13/cobra-cli
  pkgs/spf13/cobra-cli/pkg.yaml
  pkgs/spf13/cobra-cli/registry.yaml
  registry.yaml
Labels: enhancement

#8770 feat: add bufbuild/protoc-gen-validate
  pkgs/bufbuild/protoc-gen-validate/pkg.yaml
  pkgs/bufbuild/protoc-gen-validate/registry.yaml
  registry.yaml
Labels: enhancement

#8782 feat: add CycloneDX/cyclonedx-cli
  pkgs/CycloneDX/cyclonedx-cli/pkg.yaml
  pkgs/CycloneDX/cyclonedx-cli/registry.yaml
  registry.yaml
Labels: enhancement

#8785 feat: add vburenin/ifacemaker
  pkgs/vburenin/ifacemaker/pkg.yaml
  pkgs/vburenin/ifacemaker/registry.yaml
  registry.yaml
Labels: enhancement

#8786 feat: add jmattheis/goverter
  pkgs/jmattheis/goverter/pkg.yaml
  pkgs/jmattheis/goverter/registry.yaml
  registry.yaml
Labels: enhancement

#8804 feat: add ivaaaan/smug
  pkgs/ivaaaan/smug/pkg.yaml
  pkgs/ivaaaan/smug/registry.yaml
  registry.yaml
Labels: enhancement

#8810 feat: add concourse/concourse
  pkgs/concourse/concourse/concourse/pkg.yaml
  pkgs/concourse/concourse/concourse/registry.yaml
  pkgs/concourse/concourse/fly/pkg.yaml
  pkgs/concourse/concourse/fly/registry.yaml
  registry.yaml
Labels: enhancement

#8815 feat: add prometheus/prom2json
  pkgs/prometheus/prom2json/pkg.yaml
  pkgs/prometheus/prom2json/registry.yaml
  registry.yaml
Labels: enhancement

#8813 feat: add prometheus/prometheus
  pkgs/prometheus/prometheus/pkg.yaml
  pkgs/prometheus/prometheus/registry.yaml
  registry.yaml
Labels: enhancement

#8814 feat: add prometheus/alertmanager
  pkgs/prometheus/alertmanager/pkg.yaml
  pkgs/prometheus/alertmanager/registry.yaml
  registry.yaml
Labels: enhancement
