Repository aquaproj/aqua-registry, pull requests merged in 2022-03, with the labels that each got.

#2402 feat: Add afx
  pkgs/b_0.yaml
  registry.yaml
Labels: enhancement

#2403 fix: Use rosetta2 instead
  registry.yaml
Labels: target:b_0

#2404 fix: follow up #2403
  registry.yaml
Labels: target:b_0

#2475 feat: add `yannh/kubeconform`
  pkgs/y.yaml
  registry.yaml
Labels: enhancement

#2476 feat: add `zegl/kube-score`
  pkgs/z.yaml
  registry.yaml
Labels: enhancement

#2479 feat: Add deno
  pkgs/d.yaml
  pkgs/l.yaml
  registry.yaml
Labels: enhancement

#2498 feat: add `liamg/traitor` and `liamg/gitjacker`
  pkgs/l.yaml
  registry.yaml
Labels: enhancement

#2506 feat: add gokcehan/lf
  pkgs/g_1.yaml
  registry.yaml
Labels: enhancement

#2608 feat: add mszostok/codeowners-validator
  pkgs/m_1.yaml
  registry.yaml
Labels: enhancement

#2654 chore: update aqua to v1.2.0-0
  .github/workflows/actionlint.yaml
  .github/workflows/test.yaml
Labels: target:b_0

#2679 feat: add Arriven/db1000n
  pkgs/Arriven/db1000n/pkg.yaml
  registry.yaml
Labels: enhancement

#2680 docs: remove versioning policy
  README.md
Labels: enhancement

#2691 feat: add megaease/easeprobe
  pkgs/megaease/easeprobe/pkg.yaml
  registry.yaml
Labels: enhancement

#2692 feat: add ffuf/ffuf
  pkgs/ffuf/ffuf/pkg.yaml
  registry.yaml
Labels: enhancement

#2697 refactor: refactor registry.yaml
  registry.yaml
Labels: target:cli/cli, target:fishworks/gofish, target:ginuerzh/gost, target:github/hub, target:vi/websocat

#2725 fix: set supported_if
  registry.yaml
Labels: bug

#2726 fix: fix overrides of faas-cli
  registry.yaml
Labels: bug

#2728 fix: fix istioctl with overrides
  registry.yaml
Labels: bug
