Repository aquaproj/aqua-registry, pull requests merged in 2022-06, with the labels that each got.

#3759 feat: add golang.org/x/perf/cmd/benchstat
  .github/workflows/actionlint.yaml
  .github/workflows/test.yaml
  aqua-all.yaml
  pkgs/golang.org/x/perf/cmd/benchstat/pkg.yaml
  pkgs/golang.org/x/perf/cmd/benchstat/registry.yaml
  pkgs/golang.org/x/tools/cmd/goimports/pkg.yaml
  pkgs/golang.org/x/tools/cmd/goimports/registry.yaml
  pkgs/google/pprof/pkg.yaml
  pkgs/google/pprof/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3824 feat: add compose/transporter
  pkgs/compose/transporter/pkg.yaml
  pkgs/compose/transporter/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3825 feat: add kubecost/kubectl-cost
  pkgs/kubecost/kubectl-cost/pkg.yaml
  pkgs/kubecost/kubectl-cost/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3826 feat: add deepmap/oapi-codegen
  pkgs/deepmap/oapi-codegen/pkg.yaml
  pkgs/deepmap/oapi-codegen/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3830 fix: set the package name explicitly to keep the compatibility
  pkgs/golang.org/x/perf/cmd/benchstat/registry.yaml
  pkgs/golang.org/x/tools/cmd/goimports/registry.yaml
  registry.json
  registry.yaml
Labels: bug

#3882 feat: add `google/go-jsonnet`
  pkgs/google/go-jsonnet/pkg.yaml
  pkgs/google/go-jsonnet/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3889 feat: add kyleconroy/sqlc
  pkgs/kyleconroy/sqlc/pkg.yaml
  pkgs/kyleconroy/sqlc/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3891 feat: add kreuzwerker/envplate
  pkgs/kreuzwerker/envplate/pkg.yaml
  pkgs/kreuzwerker/envplate/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3892 feat: add kreuzwerker/m1-terraform-provider-helper
  pkgs/kreuzwerker/m1-terraform-provider-helper/pkg.yaml
  pkgs/kreuzwerker/m1-terraform-provider-helper/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3912 feat: add webdevops/go-crond
  pkgs/webdevops/go-crond/pkg.yaml
  pkgs/webdevops/go-crond/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3913 feat: add arl/gitmux
  pkgs/arl/gitmux/pkg.yaml
  pkgs/arl/gitmux/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3929 feat: add budimanjojo/talhelper
  pkgs/budimanjojo/talhelper/pkg.yaml
  pkgs/budimanjojo/talhelper/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3879 feat: add hadolint/hadolint
  pkgs/hadolint/hadolint/pkg.yaml
  pkgs/hadolint/hadolint/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3941 feat: add coder/coder
  pkgs/coder/coder/pkg.yaml
  pkgs/coder/coder/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3942 fix(cli/cli): support Windows
  pkgs/cli/cli/registry.yaml
  registry.json
  registry.yaml
Labels: bug

#3945 feat: add apache/camel-k (kamel)
  pkgs/apache/camel-k/pkg.yaml
  pkgs/apache/camel-k/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3947 docs: add a guide for rust
  CONTRIBUTING.md
Labels: documentation

#3948 docs: add an example
  CONTRIBUTING.md
Labels: documentation

#3949 feat: Add sheepla-wares
  pkgs/sheepla/longgopher/pkg.yaml
  pkgs/sheepla/longgopher/registry.yaml
  pkgs/sheepla/pingu/pkg.yaml
  pkgs/sheepla/pingu/registry.yaml
  pkgs/sheepla/qiitaz/registry.yaml
  pkgs/sheepla/srss/pkg.yaml
  pkgs/sheepla/srss/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3951 ADD: fujiwara/tfstate-lookup
  pkgs/fujiwara/tfstate-lookup/pkg.yaml
  pkgs/fujiwara/tfstate-lookup/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3963 fix(Songmu/ghch): enable rosetta2
  pkgs/Songmu/ghch/registry.yaml
  registry.json
  registry.yaml
Labels: bug

#3964 fix(Songmu/ghg): enable rosetta2
  pkgs/Songmu/ghg/registry.yaml
  registry.json
  registry.yaml
Labels: bug

#3965 fix(Songmu/gocredits): enable rosetta2
  pkgs/Songmu/gocredits/registry.yaml
  registry.json
  registry.yaml
Labels: bug

#3946 feat: support windows
  pkgs/1xyz/pryrite/registry.yaml
  pkgs/BurntSushi/ripgrep/registry.yaml
  pkgs/Dreamacro/clash/registry.yaml
  pkgs/MusicDin/kubitect/registry.yaml
  pkgs/Peltoche/lsd/registry.yaml
  pkgs/Shopify/ejson/registry.yaml
  pkgs/Songmu/ecschedule/registry.yaml
  pkgs/Songmu/ghch/registry.yaml
  pkgs/Songmu/ghg/registry.yaml
  pkgs/gohugoio/hugo/registry.yaml
  pkgs/golang/go/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3966 fix: support windows and arm64
  pkgs/Songmu/gotesplit/registry.yaml
  registry.json
  registry.yaml
Labels: bug

#3972 fix(Songmu/horenso): support windows and darwin/arm64
  pkgs/Songmu/horenso/registry.yaml
  registry.json
  registry.yaml
Labels: bug

#3982 fix(XAMPPRocky/tokei): windows support
  pkgs/XAMPPRocky/tokei/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3983 fix(abs-lang/abs): support windows
  pkgs/abs-lang/abs/registry.yaml
  registry.json
  registry.yaml
Labels: bug

#3989 feat: add junegunn/fzf/fzf-tmux
  pkgs/junegunn/fzf/fzf-tmux/pkg.yaml
  pkgs/junegunn/fzf/fzf-tmux/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3991 docs: add document about supported OS and CPU Architecture
  CONTRIBUTING.md
Labels: documentation

#3992 fix(aelsabbahy/goss): windows support
  pkgs/aelsabbahy/goss/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#3973 feat: Add buildkite/cli and buildkite/agent.
  pkgs/buildkite/agent/pkg.yaml
  pkgs/buildkite/agent/registry.yaml
  pkgs/buildkite/cli/pkg.yaml
  pkgs/buildkite/cli/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4015 fix: set complete_windows_exe
  pkgs/GoogleCloudPlatform/terraformer/aws/registry.yaml
  pkgs/GoogleCloudPlatform/terraformer/registry.yaml
  registry.json
  registry.yaml
Labels: bug

#4016 fix(ajeetdsouza/zoxide): windows support
  pkgs/ajeetdsouza/zoxide/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4017 fix(aquasecurity/starboard): support Windows and arm64
  pkgs/aquasecurity/starboard/pkg.yaml
  pkgs/aquasecurity/starboard/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4018 fix(argoproj-labs/argocd-autopilot): support windows
  pkgs/argoproj-labs/argocd-autopilot/registry.yaml
  registry.json
  registry.yaml
Labels: bug

#4019 fix(argoproj-labs/argocd-image-updater): windows support
  pkgs/argoproj-labs/argocd-image-updater/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4020 fix(argoproj/argo-rollouts): support arm64 and windows
  pkgs/argoproj/argo-rollouts/registry.yaml
  registry.json
  registry.yaml
Labels: bug

#4021 fix(argoproj/argo-workflows): windows support
  pkgs/argoproj/argo-workflows/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4022 feat(armosec/kubescape): support windows
  pkgs/armosec/kubescape/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4023 feat(aws/amazon-ec2-instance-selector): windows support
  pkgs/aws/amazon-ec2-instance-selector/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4024 feat(aws/copilot-cli): windows support
  pkgs/aws/copilot-cli/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4026 feat(bufbuild/buf): windows support
  pkgs/bufbuild/buf/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4027 feat(buildpacks/pack): windows support
  pkgs/buildpacks/pack/pkg.yaml
  pkgs/buildpacks/pack/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4028 feat(cheat/cheat): windows support
  pkgs/cheat/cheat/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4032 feat(compose/transporter): windows support
  pkgs/compose/transporter/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4033 feat(corneliusweig/ketall): windows support
  pkgs/corneliusweig/ketall/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4034 feat(corneliusweig/rakkess): windows support
  pkgs/corneliusweig/rakkess/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4035 feat: skip installing on windows
  pkgs/GoogleContainerTools/kpt/registry.yaml
  pkgs/Songmu/gocredits/registry.yaml
  pkgs/abiosoft/colima/registry.yaml
  pkgs/aquasecurity/trivy/registry.yaml
  pkgs/aristocratos/btop/registry.yaml
  pkgs/arl/gitmux/registry.yaml
  pkgs/b4b4r07/afx/registry.yaml
  pkgs/b4b4r07/gist/registry.yaml
  pkgs/b4b4r07/git-bump/registry.yaml
  pkgs/b4b4r07/github-labeler/registry.yaml
  pkgs/b4b4r07/gomi/registry.yaml
  pkgs/b4b4r07/iap_curl/registry.yaml
  pkgs/b4b4r07/stein/registry.yaml
  pkgs/bcicen/slackcat/registry.yaml
  pkgs/benbjohnson/litestream/registry.yaml
  pkgs/benchkram/bob/registry.yaml
  pkgs/blacknon/hwatch/registry.yaml
  pkgs/boz/kail/registry.yaml
  pkgs/budimanjojo/talhelper/registry.yaml
  pkgs/c-bata/kube-prompt/registry.yaml
  pkgs/caarlos0/fork-cleaner/registry.yaml
  pkgs/chanzuckerberg/fogg/registry.yaml
  pkgs/che-incubator/chectl/registry.yaml
  pkgs/codeclimate/test-reporter/registry.yaml
  pkgs/controlplaneio/kubesec/registry.yaml
  registry.json
  registry.yaml
Labels: bug

#4036 feat(corneliusweig/rakkess/access-matrix): windows support
  pkgs/corneliusweig/rakkess/access-matrix/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4038 feat(dandavison/delta): windows support
  pkgs/dandavison/delta/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4039 feat(dapr/cli): windows support
  pkgs/dapr/cli/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4053 fix(tenable/terrascan): remove alias
  pkgs/tenable/terrascan/registry.yaml
  registry.json
  registry.yaml
Labels: bug

#4054 feat(dhall-lang/dhall-haskell): windows support
  pkgs/dhall-lang/dhall-haskell/pkg.yaml
  pkgs/dhall-lang/dhall-haskell/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4055 feat(docker-slim/docker-slim): windows support
  pkgs/docker-slim/docker-slim/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4056 feat(dotenv-linter/dotenv-linter): windows support
  pkgs/dotenv-linter/dotenv-linter/pkg.yaml
  pkgs/dotenv-linter/dotenv-linter/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4057 feat(ducaale/xh): windows support
  pkgs/ducaale/xh/pkg.yaml
  pkgs/ducaale/xh/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4058 feat(editorconfig-checker/editorconfig-checker): windows support
  pkgs/editorconfig-checker/editorconfig-checker/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4059 feat(ernoaapa/kubectl-warp): windows support
  pkgs/ernoaapa/kubectl-warp/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4060 feat(erroneousboat/slack-term): windows support
  pkgs/erroneousboat/slack-term/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4061 feat(fatedier/frp): windows support
  pkgs/fatedier/frp/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4062 feat(fishi0x01/vsh): windows support
  pkgs/fishi0x01/vsh/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4063 feat(iam-policy-json-to-terraform): windows support
  pkgs/flosell/iam-policy-json-to-terraform/pkg.yaml
  pkgs/flosell/iam-policy-json-to-terraform/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4064 feat(fluxcd/flux2): windows support
  pkgs/fluxcd/flux2/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4065 feat: exclude windows (lambroll, tracer)
  pkgs/fujiwara/lambroll/registry.yaml
  pkgs/fujiwara/tracer/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4066 feat(genuinetools/reg): windows support
  pkgs/genuinetools/reg/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4071 feat(ginuerzh/gost): windows support
  pkgs/ginuerzh/gost/pkg.yaml
  pkgs/ginuerzh/gost/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4072 feat(git-lfs/git-lfs): windows support
  pkgs/git-lfs/git-lfs/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4073 feat(github/hub): windows support
  pkgs/github/hub/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4074 feat(gleam-lang/gleam): windows support
  pkgs/gleam-lang/gleam/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4075 feat(go-task/task): windows support
  pkgs/go-task/task/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4076 feat(gocruncher/jenkins-job-cli): windows support
  pkgs/gocruncher/jenkins-job-cli/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4077 feat(golang-migrate/migrate): windows support
  pkgs/golang-migrate/migrate/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4079 feat(golangci/golangci-lint): windows support
  pkgs/golangci/golangci-lint/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4081 feat(goreleaser/goreleaser): windows support
  pkgs/goreleaser/goreleaser/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4082 feat(gsamokovarov/jump): exclude windows
  pkgs/gsamokovarov/jump/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4083 feat(harelba/q): windows support
  pkgs/harelba/q/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4088 feat(infracost/infracost): windows support
  pkgs/infracost/infracost/pkg.yaml
  pkgs/infracost/infracost/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4089 feat(instrumenta/kubeval): windows support
  pkgs/instrumenta/kubeval/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4091 feat(jonaslu/ain): windows support
  pkgs/jonaslu/ain/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4092 feat(jreleaser/jreleaser): windows support
  pkgs/jreleaser/jreleaser/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4098 feat(junegunn/fzf): windows support
  pkgs/junegunn/fzf/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4099 feat(kanisterio/kanister): exclude windows
  pkgs/kanisterio/kanister/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4100 feat(kastenhq/external-tools): exclude windows
  pkgs/kastenhq/external-tools/k10multicluster/registry.yaml
  pkgs/kastenhq/external-tools/k10tools/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4101 feat(knqyf263/cob): exclude windows
  pkgs/knqyf263/cob/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4103 feat(kreuzwerker): exclude windows
  pkgs/kreuzwerker/awsu/registry.yaml
  pkgs/kreuzwerker/envplate/registry.yaml
  pkgs/kreuzwerker/m1-terraform-provider-helper/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4104 feat(kubecost/kubectl-cost): windows support
  pkgs/kubecost/kubectl-cost/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4105 feat(kubemqctl): windows support
  pkgs/kubemq-io/kubemqctl/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4106 feat(kind): windows support
  pkgs/kubernetes-sigs/kind/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4109 feat(kubernetes/kops): windows support
  pkgs/kubernetes/kops/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4122 feat(porter-dev/porter): ignore windows
  pkgs/porter-dev/porter/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4123 fix: exclude windows
  pkgs/kyoh86/richgo/registry.yaml
  pkgs/lima-vm/lima/registry.yaml
  pkgs/minamijoyo/tfmigrate/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4124 feat(livebud/bud): exclude windows
  pkgs/livebud/bud/registry.yaml
  pkgs/lotabout/skim/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4125 feat: windows support
  pkgs/mattn/goreman/registry.yaml
  pkgs/mattn/memo/registry.yaml
  pkgs/mercari/tfnotify/registry.yaml
  pkgs/mergestat/mergestat/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4126 feat: windows support
  pkgs/mkchoi212/fac/registry.yaml
  pkgs/mozilla/sops/pkg.yaml
  pkgs/mozilla/sops/registry.yaml
  pkgs/mumoshu/variant/registry.yaml
  pkgs/mumoshu/variant2/registry.yaml
  pkgs/mvdan/gofumpt/registry.yaml
  pkgs/nektos/act/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4127 feat(neovim/neovim): windows support
  pkgs/neovim/neovim/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4129 feat(ogham/dog): windows support
  pkgs/ogham/dog/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4184 fix: typo
  pkgs/pivotal-cf/pivnet-cli/registry.yaml
  registry.json
  registry.yaml
Labels: bug

#4187 fix: enable rosetta2
  pkgs/abiosoft/colima/pkg.yaml
  pkgs/abiosoft/colima/registry.yaml
  registry.json
  registry.yaml
Labels: bug

#4188 fix: fix supported_if
  pkgs/mozilla/sops/registry.yaml
  pkgs/thought-machine/please/registry.yaml
  pkgs/up9inc/mizu/registry.yaml
  registry.json
  registry.yaml
Labels: bug

#4195 feat: Add ipfs/go-ipfs.
  pkgs/ipfs/go-ipfs/pkg.yaml
  pkgs/ipfs/go-ipfs/registry.yaml
  registry.json
  registry.yaml
Labels: enhancement

#4243 fix: typo
  pkgs/rust-lang/mdBook/registry.yaml
  registry.json
  registry.yaml
Labels: bug

#4248 fix: exclude windows/arm64
  pkgs/dagger/dagger/registry.yaml
  pkgs/projectdiscovery/nuclei/registry.yaml
  registry.json
  registry.yaml
Labels: bug, windows

#3236 refactor: use aliases
  pkgs/accurics/terrascan/pkg.yaml
  pkgs/accurics/terrascan/registry.yaml
  pkgs/ahmetb/kubectx/kubens/registry.yaml
  pkgs/ahmetb/kubens/pkg.yaml
  pkgs/ahmetb/kubens/registry.yaml
  pkgs/siderolabs/conform/registry.yaml
  pkgs/siderolabs/talos/registry.yaml
  pkgs/talos-systems/conform/pkg.yaml
  pkgs/talos-systems/conform/registry.yaml
  pkgs/talos-systems/talos/pkg.yaml
  pkgs/talos-systems/talos/registry.yaml
  pkgs/tenable/terrascan/registry.yaml
  registry.json
  registry.yaml
Labels: breaking change

#3760 Replace go to go install
  .github/workflows/test.yaml
  pkgs/anqiansong/github-compare/registry.yaml
  pkgs/golang.org/x/perf/cmd/benchstat/registry.yaml
  pkgs/golang/tools/gopls/pkg.yaml
  pkgs/golang/tools/gopls/registry.yaml
  pkgs/google/wire/registry.yaml
  pkgs/katbyte/terrafmt/registry.yaml
  pkgs/mitchellh/gox/registry.yaml
  registry.json
  registry.yaml
Labels: breaking change

#4249 chore: remove registry.json
  .prettierignore
  CONTRIBUTING.md
  aqua-all.yaml
  aqua-ci.yaml
  aqua-dev.yaml
  generate-registry.sh
  registry.json
Labels: breaking change

#4270 docs: windows support
  CONTRIBUTING.md
Labels: documentation

#4271 feat: add nakabonne/ali
  pkgs/nakabonne/ali/pkg.yaml
  pkgs/nakabonne/ali/registry.yaml
  registry.yaml
Labels: enhancement

#4272 feat: add guptarohit/asciigraph
  pkgs/guptarohit/asciigraph/pkg.yaml
  pkgs/guptarohit/asciigraph/registry.yaml
  registry.yaml
Labels: enhancement

#4278 feat: add gomods/athens
  pkgs/gomods/athens/pkg.yaml
  pkgs/gomods/athens/registry.yaml
  registry.yaml
Labels: enhancement

#4280 feat: add liggitt/audit2rbac
  pkgs/liggitt/audit2rbac/pkg.yaml
  pkgs/liggitt/audit2rbac/registry.yaml
  registry.yaml
Labels: enhancement

#4281 feat: add wallix/awless
  pkgs/wallix/awless/pkg.yaml
  pkgs/wallix/awless/registry.yaml
  registry.yaml
Labels: enhancement

#4282 feat: add mpostument/awstaghelper
  pkgs/mpostument/awstaghelper/pkg.yaml
  pkgs/mpostument/awstaghelper/registry.yaml
  registry.yaml
Labels: enhancement

#4284 feat: add miniscruff/changie
  pkgs/miniscruff/changie/pkg.yaml
  pkgs/miniscruff/changie/registry.yaml
  registry.yaml
Labels: enhancement

#4285 feat: add helm/chart-testing
  pkgs/helm/chart-testing/pkg.yaml
  pkgs/helm/chart-testing/registry.yaml
  registry.yaml
Labels: enhancement

#4286 feat: heartbeatsjp/check-tls-cert
  pkgs/heartbeatsjp/check-tls-cert/pkg.yaml
  pkgs/heartbeatsjp/check-tls-cert/registry.yaml
  registry.yaml
Labels: enhancement

#4287 feat: add jreisinger/checkip
  pkgs/jreisinger/checkip/pkg.yaml
  pkgs/jreisinger/checkip/registry.yaml
  registry.yaml
Labels: enhancement

#4290 feat: add barnybug/cli53
  pkgs/barnybug/cli53/pkg.yaml
  pkgs/barnybug/cli53/registry.yaml
  registry.yaml
Labels: enhancement

#4291 feat: add clog-tool/clog-cli
  pkgs/clog-tool/clog-cli/pkg.yaml
  pkgs/clog-tool/clog-cli/registry.yaml
  registry.yaml
Labels: enhancement

#4294 feat: add mumoshu/config-registry
  pkgs/mumoshu/config-registry/pkg.yaml
  pkgs/mumoshu/config-registry/registry.yaml
  registry.yaml
Labels: enhancement

#4295 feat: add visma-prodsec/confused
  pkgs/visma-prodsec/confused/pkg.yaml
  pkgs/visma-prodsec/confused/registry.yaml
  registry.yaml
Labels: enhancement

#4296 feat: add sstadick/crabz
  pkgs/sstadick/crabz/pkg.yaml
  pkgs/sstadick/crabz/registry.yaml
  registry.yaml
Labels: enhancement

#4297 feat: add deref/exo
  pkgs/deref/exo/pkg.yaml
  pkgs/deref/exo/registry.yaml
  registry.yaml
Labels: enhancement

#4298 feat: add Phantas0s/devdash
  pkgs/Phantas0s/devdash/pkg.yaml
  pkgs/Phantas0s/devdash/registry.yaml
  registry.yaml
Labels: enhancement

#4312 fix(GoogleContainerTools/skaffold): exclude windows/arm64
  pkgs/GoogleContainerTools/skaffold/registry.yaml
  registry.yaml
Labels: bug

#4313 feat: add naggie/dstask
  pkgs/naggie/dstask/dstask-import/pkg.yaml
  pkgs/naggie/dstask/dstask-import/registry.yaml
  pkgs/naggie/dstask/pkg.yaml
  pkgs/naggie/dstask/registry.yaml
  registry.yaml
Labels: enhancement

#4314 feat: add devops-works/dw-query-digest
  pkgs/devops-works/dw-query-digest/pkg.yaml
  pkgs/devops-works/dw-query-digest/registry.yaml
  registry.yaml
Labels: enhancement

#4315 feat: add devops-works/egress-auditor
  pkgs/devops-works/egress-auditor/pkg.yaml
  pkgs/devops-works/egress-auditor/registry.yaml
  registry.yaml
Labels: enhancement

#4316 feat: add exoscale/cli
  pkgs/exoscale/cli/pkg.yaml
  pkgs/exoscale/cli/registry.yaml
  registry.yaml
Labels: enhancement

#4317 feat: add jtyr/gbt
  pkgs/jtyr/gbt/pkg.yaml
  pkgs/jtyr/gbt/registry.yaml
  registry.yaml
Labels: enhancement

#4318 feat: add dundee/gdu
  pkgs/dundee/gdu/pkg.yaml
  pkgs/dundee/gdu/registry.yaml
  registry.yaml
Labels: enhancement

#4324 feat: add hhatto/gocloc
  pkgs/hhatto/gocloc/pkg.yaml
  pkgs/hhatto/gocloc/registry.yaml
  registry.yaml
Labels: enhancement

#4325 feat: add praetorian-inc/gokart
  pkgs/praetorian-inc/gokart/pkg.yaml
  pkgs/praetorian-inc/gokart/registry.yaml
  registry.yaml
Labels: enhancement

#4326 feat: add Lallassu/gorss
  pkgs/Lallassu/gorss/pkg.yaml
  pkgs/Lallassu/gorss/registry.yaml
  registry.yaml
Labels: enhancement

#4327 feat: add securego/gosec
  pkgs/securego/gosec/pkg.yaml
  pkgs/securego/gosec/registry.yaml
  registry.yaml
Labels: enhancement

#4328 feat: add xxxserxxx/gotop
  pkgs/xxxserxxx/gotop/pkg.yaml
  pkgs/xxxserxxx/gotop/registry.yaml
  registry.yaml
Labels: enhancement

#4330 feat: add grafana/grafana-kiosk
  pkgs/grafana/grafana-kiosk/pkg.yaml
  pkgs/grafana/grafana-kiosk/registry.yaml
  registry.yaml
Labels: enhancement

#4346 feat: add pemistahl/grex
  pkgs/pemistahl/grex/pkg.yaml
  pkgs/pemistahl/grex/registry.yaml
  registry.yaml
Labels: enhancement

#4347 feat: add grafana/grizzly
  pkgs/grafana/grizzly/pkg.yaml
  pkgs/grafana/grizzly/registry.yaml
  registry.yaml
Labels: enhancement

#4348 feat: add tomnomnom/gron
  pkgs/tomnomnom/gron/pkg.yaml
  pkgs/tomnomnom/gron/registry.yaml
  registry.yaml
Labels: enhancement

#4349 feat: add homeport/havener
  pkgs/homeport/havener/pkg.yaml
  pkgs/homeport/havener/registry.yaml
  registry.yaml
Labels: enhancement

#4350 feat: add hetznercloud/cli
  pkgs/hetznercloud/cli/pkg.yaml
  pkgs/hetznercloud/cli/registry.yaml
  registry.yaml
Labels: enhancement

#4351 feat: add helmwave/helmwave
  pkgs/helmwave/helmwave/pkg.yaml
  pkgs/helmwave/helmwave/registry.yaml
  registry.yaml
Labels: enhancement

#4352 feat: add dstotijn/hetty
  pkgs/dstotijn/hetty/pkg.yaml
  pkgs/dstotijn/hetty/registry.yaml
  registry.yaml
Labels: enhancement

#4353 feat: add soywod/himalaya
  pkgs/soywod/himalaya/pkg.yaml
  pkgs/soywod/himalaya/registry.yaml
  registry.yaml
Labels: enhancement

#4354 feat: add iann0036/iamlive
  pkgs/iann0036/iamlive/pkg.yaml
  pkgs/iann0036/iamlive/registry.yaml
  registry.yaml
Labels: enhancement

#4355 feat: add PaulJuliusMartinez/jless
  pkgs/PaulJuliusMartinez/jless/pkg.yaml
  pkgs/PaulJuliusMartinez/jless/registry.yaml
  registry.yaml
Labels: enhancement

#4356 feat: add dtan4/k8stail
  pkgs/dtan4/k8stail/pkg.yaml
  pkgs/dtan4/k8stail/registry.yaml
  registry.yaml
Labels: enhancement

#4357 feat: add deviceinsight/kafkactl
  pkgs/deviceinsight/kafkactl/pkg.yaml
  pkgs/deviceinsight/kafkactl/registry.yaml
  registry.yaml
Labels: enhancement

#4358 feat: add quarkslab/kdigger
  pkgs/quarkslab/kdigger/pkg.yaml
  pkgs/quarkslab/kdigger/registry.yaml
  registry.yaml
Labels: enhancement
