Repository aquaproj/aqua-registry, pull requests merged in 2022-08, with the labels that each got.

#5245 feat: add slsa-framework/slsa-verifier
  pkgs/slsa-framework/slsa-verifier/pkg.yaml
  pkgs/slsa-framework/slsa-verifier/registry.yaml
  registry.yaml
Labels: enhancement

#5248 feat: Add vishaltelangre/ff
  pkgs/vishaltelangre/ff/pkg.yaml
  pkgs/vishaltelangre/ff/registry.yaml
  registry.yaml
Labels: enhancement

#5249 feat: Add high-moctane/mocword
  pkgs/high-moctane/mocword/pkg.yaml
  pkgs/high-moctane/mocword/registry.yaml
  registry.yaml
Labels: enhancement

#5250 feat: Add rhysd/vim-startuptime
  pkgs/rhysd/vim-startuptime/pkg.yaml
  pkgs/rhysd/vim-startuptime/registry.yaml
  registry.yaml
Labels: enhancement

#5251 feat: Add b3nj5m1n/xdg-ninja
  pkgs/b3nj5m1n/xdg-ninja/pkg.yaml
  pkgs/b3nj5m1n/xdg-ninja/registry.yaml
  registry.yaml
Labels: enhancement

#5252 feat: owenthereal/upterm
  pkgs/owenthereal/upterm/pkg.yaml
  pkgs/owenthereal/upterm/registry.yaml
  registry.yaml
Labels: enhancement

#5221 feat: add aquaproj/registry-tool
  pkgs/aquaproj/registry-tool/pkg.yaml
  pkgs/aquaproj/registry-tool/registry.yaml
  registry.yaml
Labels: enhancement

#5271 feat: Add Mic-U/ecsher
  pkgs/Mic-U/ecsher/pkg.yaml
  pkgs/Mic-U/ecsher/registry.yaml
  registry.yaml
Labels: enhancement

#5301 feat: add acorn-io/acorn
  pkgs/acorn-io/acorn/pkg.yaml
  pkgs/acorn-io/acorn/registry.yaml
  registry.yaml
Labels: enhancement

#5331 fix: fix test workflow
  .github/workflows/test.yaml
  aqua/ci-info.yaml
  aqua/test.yaml
Labels: target:cli/cli

#5330 feat: add sl1pm4t/k2tf
  pkgs/sl1pm4t/k2tf/pkg.yaml
  pkgs/sl1pm4t/k2tf/registry.yaml
  registry.yaml
Labels: enhancement

#5332 feat: add ViRb3/wgcf
  pkgs/ViRb3/wgcf/pkg.yaml
  pkgs/ViRb3/wgcf/registry.yaml
  registry.yaml
Labels: enhancement

#5335 feat: add zquestz/s
  pkgs/zquestz/s/pkg.yaml
  pkgs/zquestz/s/registry.yaml
  registry.yaml
Labels: enhancement

#5344 feat: Add mattn/cho
  pkgs/mattn/cho/pkg.yaml
  pkgs/mattn/cho/registry.yaml
  registry.yaml
Labels: enhancement

#5346 feat: Add itchyny/bed
  pkgs/itchyny/bed/pkg.yaml
  pkgs/itchyny/bed/registry.yaml
  registry.yaml
Labels: enhancement

#5348 feat: Add skanehira/rtty
  pkgs/skanehira/rtty/pkg.yaml
  pkgs/skanehira/rtty/registry.yaml
  registry.yaml
Labels: enhancement

#5347 feat: Add ko1nksm/getoptions
  pkgs/ko1nksm/getoptions/gengetoptions/pkg.yaml
  pkgs/ko1nksm/getoptions/gengetoptions/registry.yaml
  pkgs/ko1nksm/getoptions/pkg.yaml
  pkgs/ko1nksm/getoptions/registry.yaml
  registry.yaml
Labels: enhancement

#5345 feat: Add wtetsu/gaze
  pkgs/wtetsu/gaze/pkg.yaml
  pkgs/wtetsu/gaze/registry.yaml
  registry.yaml
Labels: enhancement

#5349 feat: add omrikiei/ktunnel
  pkgs/omrikiei/ktunnel/pkg.yaml
  pkgs/omrikiei/ktunnel/registry.yaml
  registry.yaml
Labels: enhancement

#5350 feat: add lima-vm/sshocker
  pkgs/lima-vm/sshocker/pkg.yaml
  pkgs/lima-vm/sshocker/registry.yaml
  registry.yaml
Labels: enhancement

#5354 feat: add google/gke-policy-automation
  pkgs/google/gke-policy-automation/pkg.yaml
  pkgs/google/gke-policy-automation/registry.yaml
  registry.yaml
Labels: enhancement

#5360 feat: add superbrothers/ksort
  pkgs/superbrothers/ksort/pkg.yaml
  pkgs/superbrothers/ksort/registry.yaml
  registry.yaml
Labels: enhancement

#5381 feat: add metalbear-co/mirrord
  pkgs/metalbear-co/mirrord/pkg.yaml
  pkgs/metalbear-co/mirrord/registry.yaml
  registry.yaml
Labels: enhancement

#5387 feat: add fastly/cli
  pkgs/fastly/cli/pkg.yaml
  pkgs/fastly/cli/registry.yaml
  registry.yaml
Labels: enhancement

#5389 feat: add fastly/terrctl
  pkgs/fastly/terrctl/pkg.yaml
  pkgs/fastly/terrctl/registry.yaml
  registry.yaml
Labels: enhancement

#5390 feat: add simeji/jid
  pkgs/simeji/jid/pkg.yaml
  pkgs/simeji/jid/registry.yaml
  registry.yaml
Labels: enhancement

#5485 feat: add aws/amazon-ec2-spot-interrupter
  pkgs/aws/amazon-ec2-spot-interrupter/pkg.yaml
  pkgs/aws/amazon-ec2-spot-interrupter/registry.yaml
  registry.yaml
Labels: enhancement

#5490 feat: add cycloidio/terracognita
  pkgs/cycloidio/terracognita/pkg.yaml
  pkgs/cycloidio/terracognita/registry.yaml
  registry.yaml
Labels: enhancement

#5493 feat: add hirosassa/tfcmt-gitlab
  pkgs/hirosassa/tfcmt-gitlab/pkg.yaml
  pkgs/hirosassa/tfcmt-gitlab/registry.yaml
  registry.yaml
Labels: enhancement

#5496 Update README.md
  README.md
Labels: documentation

#5501 feat: add caddyserver/caddy
  pkgs/caddyserver/caddy/pkg.yaml
  pkgs/caddyserver/caddy/registry.yaml
  registry.yaml
Labels: enhancement

#5503 feat: add kentaro-m/md2confl
  pkgs/kentaro-m/md2confl/pkg.yaml
  pkgs/kentaro-m/md2confl/registry.yaml
  registry.yaml
Labels: enhancement

#5504 feat: add muesli/gitty
  pkgs/muesli/gitty/pkg.yaml
  pkgs/muesli/gitty/registry.yaml
  registry.yaml
Labels: enhancement

#5507 feat: add minamijoyo/tfedit
  pkgs/minamijoyo/tfedit/pkg.yaml
  pkgs/minamijoyo/tfedit/registry.yaml
  registry.yaml
Labels: enhancement

#5545 feat: add k1LoW/tbls
  pkgs/k1LoW/tbls/pkg.yaml
  pkgs/k1LoW/tbls/registry.yaml
  registry.yaml
Labels: enhancement

#5554 feat: add GoogleCloudPlatform/berglas
  pkgs/GoogleCloudPlatform/berglas/pkg.yaml
  pkgs/GoogleCloudPlatform/berglas/registry.yaml
  registry.yaml
Labels: enhancement

#5555 feat: add weaveworks/tf-controller/tfctl
  pkgs/weaveworks/tf-controller/tfctl/pkg.yaml
  pkgs/weaveworks/tf-controller/tfctl/registry.yaml
  registry.yaml
Labels: enhancement

#5560 feat: add mrtazz/checkmake
  pkgs/mrtazz/checkmake/pkg.yaml
  pkgs/mrtazz/checkmake/registry.yaml
  registry.yaml
Labels: enhancement

#5565 feat: add k1LoW/octocov
  pkgs/k1LoW/octocov/pkg.yaml
  pkgs/k1LoW/octocov/registry.yaml
  registry.yaml
Labels: enhancement

#5564 feat: add fortio/fortio
  pkgs/fortio/fortio/pkg.yaml
  pkgs/fortio/fortio/registry.yaml
  registry.yaml
Labels: enhancement

#5566 feat: add jckuester/terradozer
  pkgs/jckuester/terradozer/pkg.yaml
  pkgs/jckuester/terradozer/registry.yaml
  registry.yaml
Labels: enhancement

#5577 feat: add skanehira/slack-reminder
  pkgs/skanehira/slack-reminder/pkg.yaml
  pkgs/skanehira/slack-reminder/registry.yaml
  registry.yaml
Labels: enhancement

#5578 feat: add po3rin/github_link_creator
  pkgs/po3rin/github_link_creator/pkg.yaml
  pkgs/po3rin/github_link_creator/registry.yaml
  registry.yaml
Labels: enhancement

#5582 feat: add mjibson/sqlfmt
  pkgs/mjibson/sqlfmt/pkg.yaml
  pkgs/mjibson/sqlfmt/registry.yaml
  registry.yaml
Labels: enhancement

#5584 feat: add LGUG2Z/komorebi
  pkgs/LGUG2Z/komorebi/pkg.yaml
  pkgs/LGUG2Z/komorebi/registry.yaml
  registry.yaml
Labels: enhancement

#5587 feat: add raviqqe/muffet
  pkgs/raviqqe/muffet/pkg.yaml
  pkgs/raviqqe/muffet/registry.yaml
  registry.yaml
Labels: enhancement

#5583 feat: add ericchiang/pup
  pkgs/ericchiang/pup/pkg.yaml
  pkgs/ericchiang/pup/registry.yaml
  registry.yaml
Labels: enhancement

#5594 feat: add yoheimuta/protolint
  pkgs/yoheimuta/protolint/pkg.yaml
  pkgs/yoheimuta/protolint/registry.yaml
  registry.yaml
Labels: enhancement

#5610 fix(ossf/scorecard): configure version_overrides
  pkgs/ossf/scorecard/pkg.yaml
  pkgs/ossf/scorecard/registry.yaml
  registry.yaml
Labels: bug

#5611 feat: add electric-saw/kafta
  pkgs/electric-saw/kafta/pkg.yaml
  pkgs/electric-saw/kafta/registry.yaml
  registry.yaml
Labels: enhancement

#5618 feat: add sue445/plant_erd
  pkgs/sue445/plant_erd/pkg.yaml
  pkgs/sue445/plant_erd/registry.yaml
  registry.yaml
Labels: enhancement

#5619 feat: add Songmu/godzil
  pkgs/Songmu/godzil/pkg.yaml
  pkgs/Songmu/godzil/registry.yaml
  registry.yaml
Labels: enhancement

#5626 feat: add estesp/manifest-tool
  pkgs/estesp/manifest-tool/pkg.yaml
  pkgs/estesp/manifest-tool/registry.yaml
  registry.yaml
Labels: enhancement

#5633 fix(docker/compose): fix checksum config
  pkgs/docker/compose/pkg.yaml
  pkgs/docker/compose/registry.yaml
  registry.yaml
Labels: bug

#5634 feat: add stateful/rdme
  pkgs/stateful/rdme/pkg.yaml
  pkgs/stateful/rdme/registry.yaml
  registry.yaml
Labels: enhancement

#5635 feat: add liweiyi88/gosnakego
  pkgs/liweiyi88/gosnakego/pkg.yaml
  pkgs/liweiyi88/gosnakego/registry.yaml
  registry.yaml
Labels: enhancement

#5636 feat: add charmbracelet/charm
  pkgs/charmbracelet/charm/pkg.yaml
  pkgs/charmbracelet/charm/registry.yaml
  registry.yaml
Labels: enhancement

#5637 feat: add charmbracelet/skate
  pkgs/charmbracelet/skate/pkg.yaml
  pkgs/charmbracelet/skate/registry.yaml
  registry.yaml
Labels: enhancement

#5638 feat: add filhodanuvem/gitql
  pkgs/filhodanuvem/gitql/pkg.yaml
  pkgs/filhodanuvem/gitql/registry.yaml
  registry.yaml
Labels: enhancement

#5639 feat: add a8m/envsubst
  pkgs/a8m/envsubst/pkg.yaml
  pkgs/a8m/envsubst/registry.yaml
  registry.yaml
Labels: enhancement

#5641 feat: add syncthing/syncthing
  pkgs/syncthing/syncthing/pkg.yaml
  pkgs/syncthing/syncthing/registry.yaml
  registry.yaml
Labels: enhancement

#5644 feat: add showwin/speedtest-go
  pkgs/showwin/speedtest-go/pkg.yaml
  pkgs/showwin/speedtest-go/registry.yaml
  registry.yaml
Labels: enhancement

#5645 feat: add bep/s3deploy
  pkgs/bep/s3deploy/pkg.yaml
  pkgs/bep/s3deploy/registry.yaml
  registry.yaml
Labels: enhancement

#5646 feat: add x-motemen/gobump
  pkgs/x-motemen/gobump/pkg.yaml
  pkgs/x-motemen/gobump/registry.yaml
  registry.yaml
Labels: enhancement

#5647 feat: add oras-project/oras
  pkgs/oras-project/oras/pkg.yaml
  pkgs/oras-project/oras/registry.yaml
  registry.yaml
Labels: enhancement

#5648 feat: add distribution/distribution/registry
  pkgs/distribution/distribution/registry/pkg.yaml
  pkgs/distribution/distribution/registry/registry.yaml
  registry.yaml
Labels: enhancement

#5650 feat: add ldez/prm
  pkgs/ldez/prm/pkg.yaml
  pkgs/ldez/prm/registry.yaml
  registry.yaml
Labels: enhancement

#5653 feat: add auth0/auth0-cli
  pkgs/auth0/auth0-cli/pkg.yaml
  pkgs/auth0/auth0-cli/registry.yaml
  registry.yaml
Labels: enhancement

#5651 feat: add yudai/gotty
  pkgs/yudai/gotty/pkg.yaml
  pkgs/yudai/gotty/registry.yaml
  registry.yaml
Labels: enhancement

#5649 feat: add whalebrew/whalebrew
  pkgs/whalebrew/whalebrew/pkg.yaml
  pkgs/whalebrew/whalebrew/registry.yaml
  registry.yaml
Labels: enhancement

#5657 feat: add kubernetes-sigs/cri-tools/crictl
  pkgs/kubernetes-sigs/cri-tools/crictl/pkg.yaml
  pkgs/kubernetes-sigs/cri-tools/crictl/registry.yaml
  registry.yaml
Labels: enhancement

#5660 feat: add etcd-io/etcd
  pkgs/etcd-io/etcd/pkg.yaml
  pkgs/etcd-io/etcd/registry.yaml
  registry.yaml
Labels: enhancement

#5663 feat: add momaek/authy
  pkgs/momaek/authy/pkg.yaml
  pkgs/momaek/authy/registry.yaml
  registry.yaml
Labels: enhancement

#5664 feat: add variadico/noti
  pkgs/variadico/noti/pkg.yaml
  pkgs/variadico/noti/registry.yaml
  registry.yaml
Labels: enhancement

#5665 feat: add arrow2nd/nimotsu
  pkgs/arrow2nd/nimotsu/pkg.yaml
  pkgs/arrow2nd/nimotsu/registry.yaml
  registry.yaml
Labels: enhancement

#5666 feat: add jesseduffield/lazynpm
  pkgs/jesseduffield/lazynpm/pkg.yaml
  pkgs/jesseduffield/lazynpm/registry.yaml
  registry.yaml
Labels: enhancement

#5674 feat: add kkdai/youtube
  pkgs/kkdai/youtube/pkg.yaml
  pkgs/kkdai/youtube/registry.yaml
  registry.yaml
Labels: enhancement

#5691 feat: add google/yamlfmt
  pkgs/google/yamlfmt/pkg.yaml
  pkgs/google/yamlfmt/registry.yaml
  registry.yaml
Labels: enhancement

#5692 feat: add x-motemen/blogsync
  pkgs/x-motemen/blogsync/pkg.yaml
  pkgs/x-motemen/blogsync/registry.yaml
  registry.yaml
Labels: enhancement

#5693 feat: add mutagen-io/mutagen
  pkgs/mutagen-io/mutagen/pkg.yaml
  pkgs/mutagen-io/mutagen/registry.yaml
  registry.yaml
Labels: enhancement

#5694 feat: add lotabout/rargs
  pkgs/lotabout/rargs/pkg.yaml
  pkgs/lotabout/rargs/registry.yaml
  registry.yaml
Labels: enhancement

#5699 feat: add sachaos/go-life
  pkgs/sachaos/go-life/pkg.yaml
  pkgs/sachaos/go-life/registry.yaml
  registry.yaml
Labels: enhancement

#5706 feat: add pan-net-security/kcount
  pkgs/pan-net-security/kcount/pkg.yaml
  pkgs/pan-net-security/kcount/registry.yaml
  registry.yaml
Labels: enhancement

#5716 feat: add filebrowser/filebrowser
  pkgs/filebrowser/filebrowser/pkg.yaml
  pkgs/filebrowser/filebrowser/registry.yaml
  registry.yaml
Labels: enhancement

#5744 feat: add google/mtail
  pkgs/google/mtail/pkg.yaml
  pkgs/google/mtail/registry.yaml
  registry.yaml
Labels: enhancement

#5750 feat: add MichaelMure/git-bug
  pkgs/MichaelMure/git-bug/pkg.yaml
  pkgs/MichaelMure/git-bug/registry.yaml
  registry.yaml
Labels: enhancement

#5753 feat: add ankitpokhrel/jira-cli
  pkgs/ankitpokhrel/jira-cli/pkg.yaml
  pkgs/ankitpokhrel/jira-cli/registry.yaml
  registry.yaml
Labels: enhancement

#5755 feat: add ibotta/sopstool
  pkgs/ibotta/sopstool/pkg.yaml
  pkgs/ibotta/sopstool/registry.yaml
  registry.yaml
Labels: enhancement

#5757 feat: add sheepla/gofind
  pkgs/sheepla/gofind/pkg.yaml
  pkgs/sheepla/gofind/registry.yaml
  registry.yaml
Labels: enhancement

#5742 feat: add `twistedpair/google-cloud-sdk`
  pkgs/twistedpair/google-cloud-sdk/pkg.yaml
  pkgs/twistedpair/google-cloud-sdk/registry.yaml
  registry.yaml
Labels: enhancement

#5780 feat: add cubicdaiya/nginx-build
  pkgs/cubicdaiya/nginx-build/pkg.yaml
  pkgs/cubicdaiya/nginx-build/registry.yaml
  registry.yaml
Labels: enhancement

#5822 fix(gohugoio/hugo): darwin universal binary
  pkgs/gohugoio/hugo/pkg.yaml
  pkgs/gohugoio/hugo/registry.yaml
  registry.yaml
Labels: bug

#5823 feat: add jetpack-io/devbox
  pkgs/jetpack-io/devbox/pkg.yaml
  pkgs/jetpack-io/devbox/registry.yaml
  registry.yaml
Labels: enhancement

#5824 feat: add itchyny/json2yaml
  pkgs/itchyny/json2yaml/pkg.yaml
  pkgs/itchyny/json2yaml/registry.yaml
  registry.yaml
Labels: enhancement

#5825 feat: add itchyny/fillin
  pkgs/itchyny/fillin/pkg.yaml
  pkgs/itchyny/fillin/registry.yaml
  registry.yaml
Labels: enhancement

#5836 feat: add thestormforge/optimize-controller
  pkgs/thestormforge/optimize-controller/pkg.yaml
  pkgs/thestormforge/optimize-controller/registry.yaml
  registry.yaml
Labels: enhancement

#5837 feat: add pachyderm/pachyderm
  pkgs/pachyderm/pachyderm/pkg.yaml
  pkgs/pachyderm/pachyderm/registry.yaml
  registry.yaml
Labels: enhancement

#5842 fix(mikefarah/yq): disable checksum verification
  pkgs/mikefarah/yq/registry.yaml
  registry.yaml
Labels: bug

#5860 feat: add mathew-fleisch/bashbot
  pkgs/mathew-fleisch/bashbot/pkg.yaml
  pkgs/mathew-fleisch/bashbot/registry.yaml
  registry.yaml
Labels: enhancement

#5859 feat: add jenkins-x/jx
  pkgs/jenkins-x/jx/pkg.yaml
  pkgs/jenkins-x/jx/registry.yaml
  registry.yaml
Labels: enhancement

#5861 feat: add kubernetes-sigs/aws-iam-authenticator
  pkgs/kubernetes-sigs/aws-iam-authenticator/pkg.yaml
  pkgs/kubernetes-sigs/aws-iam-authenticator/registry.yaml
  registry.yaml
Labels: enhancement

#5843 feat: add linkerd/linkerd2
  pkgs/linkerd/linkerd2/pkg.yaml
  pkgs/linkerd/linkerd2/registry.yaml
  registry.yaml
Labels: enhancement

#5862 feat: add binwiederhier/ntfy
  pkgs/binwiederhier/ntfy/pkg.yaml
  pkgs/binwiederhier/ntfy/registry.yaml
  registry.yaml
Labels: enhancement

#5864 feat: add fujiwara/ecrm
  pkgs/fujiwara/ecrm/pkg.yaml
  pkgs/fujiwara/ecrm/registry.yaml
  registry.yaml
Labels: enhancement

#5886 feat: add sdslabs/gasper
  pkgs/sdslabs/gasper/pkg.yaml
  pkgs/sdslabs/gasper/registry.yaml
  registry.yaml
Labels: enhancement

#5887 feat: add bloznelis/typioca
  pkgs/bloznelis/typioca/pkg.yaml
  pkgs/bloznelis/typioca/registry.yaml
  registry.yaml
Labels: enhancement

#5888 feat: add goark/gimei-cli
  pkgs/goark/gimei-cli/pkg.yaml
  pkgs/goark/gimei-cli/registry.yaml
  registry.yaml
Labels: enhancement

#5891 feat: add jamesWoolfenden/pike
  pkgs/jamesWoolfenden/pike/pkg.yaml
  pkgs/jamesWoolfenden/pike/registry.yaml
  registry.yaml
Labels: enhancement
