Repository aquaproj/aqua-registry, pull requests merged in 2022-07, with the labels that each got.

#4538 feat: add kubernetes-sigs/controller-tools/controller-gen
  pkgs/kubernetes-sigs/controller-tools/controller-gen/pkg.yaml
  pkgs/kubernetes-sigs/controller-tools/controller-gen/registry.yaml
  registry.yaml
Labels: enhancement

#4547 feat(cli/cli): add github to search_words
  pkgs/cli/cli/registry.yaml
  registry.yaml
Labels: enhancement

#4546 feat: add github/licensed
  pkgs/github/licensed/pkg.yaml
  pkgs/github/licensed/registry.yaml
  registry.yaml
Labels: enhancement

#4565 feat: add mercari/hcledit
  pkgs/mercari/hcledit/pkg.yaml
  pkgs/mercari/hcledit/registry.yaml
  registry.yaml
Labels: enhancement

#4566 feat: add bojand/ghz
  pkgs/bojand/ghz/pkg.yaml
  pkgs/bojand/ghz/registry.yaml
  registry.yaml
Labels: enhancement

#4568 feat: add arduino/arduino-cli
  pkgs/arduino/arduino-cli/pkg.yaml
  pkgs/arduino/arduino-cli/registry.yaml
  registry.yaml
Labels: enhancement

#4574 feat: add go-swagger/go-swagger
  pkgs/go-swagger/go-swagger/pkg.yaml
  pkgs/go-swagger/go-swagger/registry.yaml
  registry.yaml
Labels: enhancement

#4579 feat: add ktock/buildg
  pkgs/ktock/buildg/pkg.yaml
  pkgs/ktock/buildg/registry.yaml
  registry.yaml
Labels: enhancement

#4580 feat: Add ninja-build/ninja
  pkgs/ninja-build/ninja/pkg.yaml
  pkgs/ninja-build/ninja/registry.yaml
  registry.yaml
Labels: enhancement

#4595 fix(kubernetes-sigs/cluster-api): exclude windows/arm64
  pkgs/kubernetes-sigs/cluster-api/registry.yaml
  registry.yaml
Labels: bug

#4596 fix(cheat/cheat): support cheat windows >= v4.2.4
  pkgs/cheat/cheat/pkg.yaml
  pkgs/cheat/cheat/registry.yaml
  registry.yaml
Labels: bug

#4597 feat: add turbot/steampipe
  pkgs/turbot/steampipe/pkg.yaml
  pkgs/turbot/steampipe/registry.yaml
  registry.yaml
Labels: enhancement

#4598 docs: update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#4602 feat: add operator-framework/operator-registry (opm)
  pkgs/operator-framework/operator-registry/pkg.yaml
  pkgs/operator-framework/operator-registry/registry.yaml
  registry.yaml
Labels: enhancement

#4581 fix: Correct asset format and supported_envs
  pkgs/b4b4r07/gomi/pkg.yaml
  pkgs/b4b4r07/gomi/registry.yaml
  pkgs/ogham/exa/registry.yaml
  pkgs/x-motemen/ghq/pkg.yaml
  pkgs/x-motemen/ghq/registry.yaml
  registry.yaml
Labels: bug

#4613 ADD: amazon-ecr-credential-helper
  pkgs/awslabs/amazon-ecr-credential-helper/pkg.yaml
  pkgs/awslabs/amazon-ecr-credential-helper/registry.yaml
  registry.yaml
Labels: enhancement

#4645 feat: add drlau/akashi
  pkgs/drlau/akashi/pkg.yaml
  pkgs/drlau/akashi/registry.yaml
  registry.yaml
Labels: enhancement

#4652 fix(buildkite/agent): support windows
  pkgs/buildkite/agent/registry.yaml
  registry.yaml
Labels: bug

#4672 feat: add TaKO8Ki/gobang
  pkgs/TaKO8Ki/gobang/pkg.yaml
  pkgs/TaKO8Ki/gobang/registry.yaml
  registry.yaml
Labels: enhancement

#4673 feat: add TaKO8Ki/frum
  pkgs/TaKO8Ki/frum/pkg.yaml
  pkgs/TaKO8Ki/frum/registry.yaml
  registry.yaml
Labels: enhancement

#4674 feat: add Jarred-Sumner/bun
  pkgs/Jarred-Sumner/bun/pkg.yaml
  pkgs/Jarred-Sumner/bun/registry.yaml
  registry.yaml
Labels: enhancement

#4687 fix(grafana/loki/logcli): support windows
  pkgs/grafana/loki/logcli/registry.yaml
  registry.yaml
Labels: bug

#4688 feat: add aquasecurity/chain-bench
  pkgs/aquasecurity/chain-bench/pkg.yaml
  pkgs/aquasecurity/chain-bench/registry.yaml
  registry.yaml
Labels: enhancement

#4696 fix: support schollz/croc v9.6.0
  pkgs/schollz/croc/pkg.yaml
  pkgs/schollz/croc/registry.yaml
  registry.yaml
Labels: bug

#4708 feat: add jiro4989/relma
  pkgs/jiro4989/relma/pkg.yaml
  pkgs/jiro4989/relma/registry.yaml
  registry.yaml
Labels: enhancement

#4709 feat: add jiro4989/textimg
  pkgs/jiro4989/textimg/pkg.yaml
  pkgs/jiro4989/textimg/registry.yaml
  registry.yaml
Labels: enhancement

#4719 docs: move document to the official site
  CONTRIBUTING.md
  README.md
Labels: documentation

#4720 docs: fix typo
  CONTRIBUTING.md
Labels: documentation

#4740 fix(gcla/termshark): exclude windows/arm64
  pkgs/gcla/termshark/registry.yaml
  registry.yaml
Labels: bug

#4761 feat: add cloudflare/gokey
  pkgs/cloudflare/gokey/pkg.yaml
  pkgs/cloudflare/gokey/registry.yaml
  registry.yaml
Labels: enhancement

#4774 docs: remove scaffold.sh from document
  CONTRIBUTING.md
Labels: documentation

#4788 feat: add updatecli/updatecli
  pkgs/updatecli/updatecli/pkg.yaml
  pkgs/updatecli/updatecli/registry.yaml
  registry.yaml
Labels: enhancement

#4797 fix(hashicorp/nomad): exclude windows/arm64 and disable rosetta2 from v1.2.7
  pkgs/hashicorp/nomad/pkg.yaml
  pkgs/hashicorp/nomad/registry.yaml
  registry.yaml
Labels: bug

#4805 feat: add itamae-kitchen/mitamae
  pkgs/itamae-kitchen/mitamae/pkg.yaml
  pkgs/itamae-kitchen/mitamae/registry.yaml
  registry.yaml
Labels: enhancement

#4807 feat: add aws/aws-cli
  pkgs/aws/aws-cli/pkg.yaml
  pkgs/aws/aws-cli/registry.yaml
  registry.yaml
Labels: enhancement

#4810 feat: add marp-team/marp-cli
  pkgs/marp-team/marp-cli/pkg.yaml
  pkgs/marp-team/marp-cli/registry.yaml
  registry.yaml
Labels: enhancement

#4821 feat: add cloud-hypervisor/cloud-hypervisor
  pkgs/cloud-hypervisor/cloud-hypervisor/ch-remote/pkg.yaml
  pkgs/cloud-hypervisor/cloud-hypervisor/ch-remote/registry.yaml
  pkgs/cloud-hypervisor/cloud-hypervisor/pkg.yaml
  pkgs/cloud-hypervisor/cloud-hypervisor/registry.yaml
  registry.yaml
Labels: enhancement

#4820 feat: add firecracker-microvm/firecracker
  pkgs/firecracker-microvm/firecracker/pkg.yaml
  pkgs/firecracker-microvm/firecracker/registry.yaml
  registry.yaml
Labels: enhancement

#4818 feat: add docker/cli
  pkgs/docker/cli/pkg.yaml
  pkgs/docker/cli/registry.yaml
  pkgs/docker/cli/rootless/pkg.yaml
  pkgs/docker/cli/rootless/registry.yaml
  registry.yaml
Labels: enhancement

#4830 fix(crossplane/crossplane): exclude windows/arm64
  pkgs/crossplane/crossplane/registry.yaml
  registry.yaml
Labels: bug

#4819 feat: add docker/compose
  pkgs/docker/compose/pkg.yaml
  pkgs/docker/compose/registry.yaml
  registry.yaml
Labels: enhancement

#4832 fix(docker/cli): Add files even in linux
  pkgs/docker/cli/registry.yaml
  registry.yaml
Labels: bug

#4877 feat: Add jiro4989/ojosama
  pkgs/jiro4989/ojosama/pkg.yaml
  pkgs/jiro4989/ojosama/registry.yaml
  registry.yaml
Labels: enhancement

#4875 feat: Add rust-lang/rust-analyzer
  pkgs/rust-lang/rust-analyzer/pkg.yaml
  pkgs/rust-lang/rust-analyzer/registry.yaml
  registry.yaml
Labels: enhancement

#4878 feat: Add mattn/efm-langserver
  pkgs/mattn/efm-langserver/pkg.yaml
  pkgs/mattn/efm-langserver/registry.yaml
  registry.yaml
Labels: enhancement

#4885 feat: add stoplightio/spectral
  pkgs/stoplightio/spectral/pkg.yaml
  pkgs/stoplightio/spectral/registry.yaml
  registry.yaml
Labels: enhancement

#4889 feat: add kevwan/tproxy
  pkgs/kevwan/tproxy/pkg.yaml
  pkgs/kevwan/tproxy/registry.yaml
  registry.yaml
Labels: enhancement

#4901 fix: support hashicorp/terraform darwin/arm64 < 1.0.2
  pkgs/hashicorp/terraform/pkg.yaml
  pkgs/hashicorp/terraform/registry.yaml
  registry.yaml
Labels: bug

#4899 feat: add github.com/zeromicro/go-zero/tools/goctl
  pkgs/github.com/zeromicro/go-zero/tools/goctl/pkg.yaml
  pkgs/github.com/zeromicro/go-zero/tools/goctl/registry.yaml
  registry.yaml
Labels: enhancement

#4903 feat: Add greymd/teip
  pkgs/greymd/teip/pkg.yaml
  pkgs/greymd/teip/registry.yaml
  registry.yaml
Labels: enhancement

#4935 style: format
  pkgs/aquasecurity/trivy/registry.yaml
  pkgs/argoproj-labs/argocd-autopilot/registry.yaml
  pkgs/argoproj-labs/argocd-image-updater/registry.yaml
  pkgs/argoproj/argo-cd/registry.yaml
  pkgs/argoproj/argo-rollouts/registry.yaml
  pkgs/argoproj/argo-workflows/registry.yaml
  pkgs/aristocratos/btop/registry.yaml
  pkgs/arl/gitmux/registry.yaml
  pkgs/armosec/kubescape/registry.yaml
  pkgs/aws/amazon-ec2-instance-selector/registry.yaml
  pkgs/npryce/adr-tools/registry.yaml
  pkgs/ossf/scorecard/registry.yaml
  pkgs/peco/peco/registry.yaml
  pkgs/rclone/rclone/registry.yaml
  pkgs/rebuy-de/aws-nuke/registry.yaml
  pkgs/restic/restic/registry.yaml
  pkgs/rhysd/hgrep/registry.yaml
  pkgs/rlmcpherson/s3gof3r/registry.yaml
  pkgs/s0md3v/Smap/registry.yaml
  pkgs/sanathp/statusok/registry.yaml
  registry.yaml
Labels: bug

#4992 feat: add kevwan/depu
  pkgs/kevwan/depu/pkg.yaml
  pkgs/kevwan/depu/registry.yaml
  registry.yaml
Labels: enhancement

#4993 fix: deal with the rename of go-ipfs
  pkgs/ipfs/go-ipfs/pkg.yaml
  pkgs/ipfs/go-ipfs/registry.yaml
  pkgs/ipfs/kubo/pkg.yaml
  pkgs/ipfs/kubo/registry.yaml
  registry.yaml
Labels: bug

#5025 fix(cue-lang/cue): set version_overrides
  pkgs/cue-lang/cue/pkg.yaml
  pkgs/cue-lang/cue/registry.yaml
  registry.yaml
Labels: bug

#5027 feat: add hktalent/scan4all
  pkgs/hktalent/scan4all/pkg.yaml
  pkgs/hktalent/scan4all/registry.yaml
  registry.yaml
Labels: enhancement

#5044 ci: install Go only when Go is required
  .github/workflows/test.yaml
Labels: target:anqiansong/github-compare

#5048 feat: add arrow2nd/nekome
  pkgs/arrow2nd/nekome/pkg.yaml
  pkgs/arrow2nd/nekome/registry.yaml
  registry.yaml
Labels: enhancement

#5053 feat: Add b4b4r07/changed-objects
  pkgs/b4b4r07/changed-objects/pkg.yaml
  pkgs/b4b4r07/changed-objects/registry.yaml
  registry.yaml
Labels: enhancement

#5054 feat: Add skanehira/gjo
  pkgs/skanehira/gjo/pkg.yaml
  pkgs/skanehira/gjo/registry.yaml
  registry.yaml
Labels: enhancement

#5058 feat: add numtide/treefmt
  pkgs/numtide/treefmt/pkg.yaml
  pkgs/numtide/treefmt/registry.yaml
  registry.yaml
Labels: enhancement

#5059 feat: add ekzhang/bore
  pkgs/ekzhang/bore/pkg.yaml
  pkgs/ekzhang/bore/registry.yaml
  registry.yaml
Labels: enhancement

#5086 fix(buildkite/cli): support v2 in Windows
  pkgs/buildkite/cli/pkg.yaml
  pkgs/buildkite/cli/registry.yaml
  registry.yaml
Labels: bug

#5095 fix(projectdiscovery/naabu): set version_overrides
  pkgs/projectdiscovery/naabu/pkg.yaml
  pkgs/projectdiscovery/naabu/registry.yaml
  registry.yaml
Labels: bug

#5107 feat: add rapiz1/catp
  pkgs/rapiz1/catp/pkg.yaml
  pkgs/rapiz1/catp/registry.yaml
  registry.yaml
Labels: enhancement

#5127 fix(pulumi/pulumi): support pulumi >= v3.37.0 in Windows
  pkgs/pulumi/pulumi/pkg.yaml
  pkgs/pulumi/pulumi/registry.yaml
  registry.yaml
Labels: bug

#5135 feat: Add jez/as-tree
  pkgs/jez/as-tree/pkg.yaml
  pkgs/jez/as-tree/registry.yaml
  registry.yaml
Labels: enhancement

#5136 feat: Add fiatjaf/jiq
  pkgs/fiatjaf/jiq/pkg.yaml
  pkgs/fiatjaf/jiq/registry.yaml
  registry.yaml
Labels: enhancement

#5175 feat: add charmbracelet/gum
  pkgs/charmbracelet/gum/pkg.yaml
  pkgs/charmbracelet/gum/registry.yaml
  registry.yaml
Labels: enhancement

#5182 feat: add nushell/nushell
  pkgs/nushell/nushell/pkg.yaml
  pkgs/nushell/nushell/registry.yaml
  registry.yaml
Labels: enhancement

#5183 feat: Add MiSawa/xq
  pkgs/MiSawa/xq/pkg.yaml
  pkgs/MiSawa/xq/registry.yaml
  registry.yaml
Labels: enhancement

#5185 feat: Add itchyny/gojo
  pkgs/itchyny/gojo/pkg.yaml
  pkgs/itchyny/gojo/registry.yaml
  registry.yaml
Labels: enhancement

#5184 feat: Add ddddddO/gtree
  pkgs/ddddddO/gtree/pkg.yaml
  pkgs/ddddddO/gtree/registry.yaml
  registry.yaml
Labels: enhancement
