Repository aquaproj/aqua-registry, pull requests merged in 2022-01, with the labels that each got.

#1617 feat: add repo_owner and repo_name
  registry.yaml
Labels: enhancement

#1629 feat: add `version_filter` to `kubernetes-sigs/kustomize`
  .github/workflows/test.yaml
  registry.yaml
  renovate.json5
Labels: enhancement

#1631 refactor: remove link and files
  CONTRIBUTING.md
  registry.yaml
Labels: breaking change

#1632 fix: rename the command of codeclimate/test-reporter
  .github/workflows/test.yaml
  registry.yaml
Labels: breaking change, target:c

#1633 chore: update cmdx config
  .cmdx.yaml
Labels: target:a

#1678 feat: add `ryane/kfilt`
  pkgs/r.yaml
  registry.yaml
Labels: enhancement

#1691 feat: add `ahmetb/kubectx/kubens`
  pkgs/a.yaml
  registry.yaml
Labels: enhancement

#1720 feat: add `errata-ai/vale`
  pkgs/e.yaml
  registry.yaml
Labels: enhancement

#1772 feat: add `nikochiko/autosaved`
  pkgs/n.yaml
  registry.yaml
Labels: enhancement

#1831 feat: add `replicatedhq/kots`
  pkgs/r.yaml
  registry.yaml
Labels: enhancement

#1836 fix: fix `replicatedhq/kots`
  registry.yaml
Labels: bug, target:r

#1837 chore: update aqua
  .github/workflows/test.yaml
Labels: target:a

#1856 feat: add `cycloidio/inframap`
  pkgs/c.yaml
  registry.yaml
Labels: enhancement

#1857 fix: support `replicatedhq/kots` < 1.59.2
  registry.yaml
Labels: bug, target:r

#1866 feat: add `tmccombs/hcl2json`
  pkgs/t.yaml
  registry.yaml
Labels: enhancement

#1874 feat: add `pressly/goose`
  pkgs/p.yaml
  registry.yaml
Labels: enhancement

#1875 feat: add `ossf/scorecard`
  pkgs/o.yaml
  registry.yaml
Labels: enhancement

#1884 feat: add `fujiwara/tracer`
  pkgs/f.yaml
  registry.yaml
Labels: enhancement

#1912 chore: update aqua and aqua-installer
  .github/workflows/test.yaml
Labels: target:a

#1913 feat: add `Cian911/switchboard`
  pkgs/c.yaml
  registry.yaml
Labels: enhancement
