Repository aquaproj/aqua-registry, pull requests merged in 2022-02, with the labels that each got.

#2058 feat: add `charmbracelet/glow`
  pkgs/c.yaml
  pkgs/j.yaml
  registry.yaml
Labels: enhancement

#2153 Fix arm64 asset pattern
  registry.yaml
Labels: bug

#2194 add blacknon/hwatch
  pkgs/b.yaml
  registry.yaml
Labels: enhancement

#2234 add btop
  pkgs/a.yaml
  registry.yaml
Labels: enhancement

#2241 add yamllint to catch errors
  .github/workflows/yamllint.yaml
  .yamllint.yaml
  registry.yaml
Labels: bug, target:h

#2283 feat: add aws/amazon-ec2-instance-selector
  pkgs/a.yaml
  registry.yaml
Labels: enhancement

#2287 docs: add tips
  README.md
  aqua-all.yaml
Labels: target:c

#2288 docs: fix typo
  README.md
Labels: documentation, target:h

#2310 feat: add `aws-containers/amazon-ecs-exec-checker` and `orisano/dlayer`
  pkgs/a.yaml
  pkgs/o.yaml
  registry.yaml
Labels: enhancement

#2328 add caarlos0/fork-cleaner
  pkgs/c.yaml
  registry.yaml
Labels: enhancement

#2339 docs: fix tips
  README.md
Labels: documentation, target:r

#2345 feat: add `SpectralOps/teller`
  pkgs/a_0.yaml
  pkgs/a_1.yaml
  pkgs/b_0.yaml
  pkgs/b_1.yaml
  pkgs/c_0.yaml
  pkgs/c_1.yaml
  pkgs/g_0.yaml
  pkgs/g_1.yaml
  pkgs/k_0.yaml
  pkgs/k_1.yaml
  pkgs/m_0.yaml
  pkgs/m_1.yaml
  pkgs/s_0.yaml
  pkgs/s_1.yaml
  pkgs/t_0.yaml
  pkgs/t_1.yaml
  registry.yaml
Labels: enhancement
