Repository aquaproj/aqua-registry, pull requests merged in 2023-01, with the labels that each got.

#8836 docs: fix git command
  CONTRIBUTING.md
Labels: documentation

#8850 feat: add cocogitto/cocogitto
  pkgs/cocogitto/cocogitto/pkg.yaml
  pkgs/cocogitto/cocogitto/registry.yaml
  registry.yaml
Labels: enhancement

#8852 feat: add terrastruct/d2
  pkgs/terrastruct/d2/pkg.yaml
  pkgs/terrastruct/d2/registry.yaml
  registry.yaml
Labels: enhancement

#8853 feat: add terrastruct/tala
  pkgs/terrastruct/tala/pkg.yaml
  pkgs/terrastruct/tala/registry.yaml
  registry.yaml
Labels: enhancement

#8856 feat: add MordechaiHadad/bob
  pkgs/MordechaiHadad/bob/pkg.yaml
  pkgs/MordechaiHadad/bob/registry.yaml
  registry.yaml
Labels: enhancement

#8879 fix(fastly/cli): support windows
  pkgs/fastly/cli/pkg.yaml
  pkgs/fastly/cli/registry.yaml
  registry.yaml
Labels: bug

#8917 feat: add github-release/github-release
  pkgs/github-release/github-release/pkg.yaml
  pkgs/github-release/github-release/registry.yaml
  registry.yaml
Labels: enhancement

#8976 feat: add koki-develop/clive
  pkgs/koki-develop/clive/pkg.yaml
  pkgs/koki-develop/clive/registry.yaml
  registry.yaml
Labels: enhancement

#8984 feat: add tamasfe/taplo
  pkgs/tamasfe/taplo/pkg.yaml
  pkgs/tamasfe/taplo/registry.yaml
  registry.yaml
Labels: enhancement

#8988 feat: add tamasfe/taplo/full
  pkgs/tamasfe/taplo/full/pkg.yaml
  pkgs/tamasfe/taplo/full/registry.yaml
  registry.yaml
Labels: enhancement

#8989 feat: add lycheeverse/lychee
  pkgs/lycheeverse/lychee/pkg.yaml
  pkgs/lycheeverse/lychee/registry.yaml
  registry.yaml
Labels: enhancement

#9004 feat: add mgunyho/tere
  pkgs/mgunyho/tere/pkg.yaml
  pkgs/mgunyho/tere/registry.yaml
  registry.yaml
Labels: enhancement

#9029 fix(geofffranks/spruce): follow up changes in v1.30.0
  pkgs/geofffranks/spruce/pkg.yaml
  pkgs/geofffranks/spruce/registry.yaml
  registry.yaml
Labels: bug

#9053 feat: add Kampfkarren/selene
  pkgs/Kampfkarren/selene/pkg.yaml
  pkgs/Kampfkarren/selene/registry.yaml
  registry.yaml
Labels: enhancement

#9054 feat: add Kampfkarren/selene/light
  pkgs/Kampfkarren/selene/light/pkg.yaml
  pkgs/Kampfkarren/selene/light/registry.yaml
  registry.yaml
Labels: enhancement

#9064 fix(geofffranks/spruce): follow up changes in spruce v1.30.0
  pkgs/geofffranks/spruce/pkg.yaml
  pkgs/geofffranks/spruce/registry.yaml
  registry.yaml
Labels: bug

#9144 fix(koki-develop/clive): follow up changes in v0.10.2
  pkgs/koki-develop/clive/pkg.yaml
  pkgs/koki-develop/clive/registry.yaml
  registry.yaml
Labels: bug

#9221 feat: add spotDL/spotify-downloader
  pkgs/spotDL/spotify-downloader/pkg.yaml
  pkgs/spotDL/spotify-downloader/registry.yaml
  registry.yaml
Labels: enhancement

#9232 feat: add comtrya/comtrya
  pkgs/comtrya/comtrya/pkg.yaml
  pkgs/comtrya/comtrya/registry.yaml
  registry.yaml
Labels: enhancement

#9233 feat: add topgrade-rs/topgrade
  pkgs/topgrade-rs/topgrade/pkg.yaml
  pkgs/topgrade-rs/topgrade/registry.yaml
  registry.yaml
Labels: enhancement

#9242 fix(cloudquery/cloudquery): fix invalid version constraint
  pkgs/cloudquery/cloudquery/registry.yaml
  registry.yaml
Labels: bug

#9302 feat: add suzuki-shunsuke/ghalint
  pkgs/suzuki-shunsuke/ghalint/pkg.yaml
  pkgs/suzuki-shunsuke/ghalint/registry.yaml
  registry.yaml
Labels: enhancement

#9304 feat: add projectdiscovery/pdtm
  pkgs/projectdiscovery/pdtm/pkg.yaml
  pkgs/projectdiscovery/pdtm/registry.yaml
  registry.yaml
Labels: enhancement

#9305 docs: update the example of `aqua g`
  README.md
Labels: documentation

#9343 ci: restirct the scope of secrets
  .github/workflows/test.yaml
Labels: security

#9375 feat: add mutagen-io/mutagen-compose
  pkgs/mutagen-io/mutagen-compose/pkg.yaml
  pkgs/mutagen-io/mutagen-compose/registry.yaml
  registry.yaml
Labels: enhancement

#9463 feat: add kubermatic/kubeone
  pkgs/kubermatic/kubeone/pkg.yaml
  pkgs/kubermatic/kubeone/registry.yaml
  registry.yaml
Labels: enhancement

#9464 feat: add elsesiy/kubectl-view-secret
  pkgs/elsesiy/kubectl-view-secret/pkg.yaml
  pkgs/elsesiy/kubectl-view-secret/registry.yaml
  registry.yaml
Labels: enhancement

#9469 feat: add sunny0826/kubecm
  pkgs/sunny0826/kubecm/pkg.yaml
  pkgs/sunny0826/kubecm/registry.yaml
  registry.yaml
Labels: enhancement

#9474 feat: add rhysd/dotfiles
  pkgs/rhysd/dotfiles/pkg.yaml
  pkgs/rhysd/dotfiles/registry.yaml
  registry.yaml
Labels: enhancement

#9483 feat: add ms-jpq/sad
  pkgs/ms-jpq/sad/pkg.yaml
  pkgs/ms-jpq/sad/registry.yaml
  registry.yaml
Labels: enhancement
